### PR TITLE
Use config.storage.sync to instantiate the FileStorage

### PR DESCRIPTION
**Pull request by webflo**
This should make [config_split](https://www.drupal.org/project/config_split) compatible cex/cim.

### CODE REVIEW

**Comment by weitzman** [comment]
LGTM. We had a spurious test fail that cleared up on re-test.

I can merge this once you think it is complete. I notice that the title says WIP.

**Comment by webflo** [comment]
Lets get some feedback from config_split maintainers first.

**Comment by weitzman** [comment]
Any feedback yet?

**Comment by swentel** [comment]
Not a maintainer, but supporter and user. Patch makes very much sense, so +1!

**Comment by weitzman** [comment]
FYI I added back storage filters hook in #2314 for better integration with config_split. Not sure if this PR is still desirable/needed.

**Comment by bircher** [comment]
I am a maintainer of config_split and I love this PR. In fact this would be a far superior approach to storage filters.
I am moving to an approach that I swap out the `config.storage.sync` service and return the wrapped storage that unites the main directory and the split directories of the active splits. If drush would use that storage I could even think about retiring the custom commands for importing and exporting.
The storage filters - while inspired by the storage filter drush uses - would mean a much more complex interaction, I just recently had to change the interface a bit to fix a bug and that would require a change to drush etc. In addition, if drush and drupal console and drupal core all use the same service all work as expected.

The only thing that might need extra work would be the extra functionality drush cex and cim have such as automatically committing to git etc. But in my opinion that is not really blocking.

**Comment by webflo** [comment]
Alright, i think we have agreement. LGTM :)

**Comment by weitzman** [comment]
Merged into master and 8.x. I think we can get rid of Drush's filter and our filter hook and just expect folks to take over the sync service. What do folks think?

**Comment by bkosborne** [comment]
Now that Drush 8.1.10 has been released and includes this code, what needs to be done on my end to get drush cex/cim aware of config split?

**Comment by weitzman** [comment]
Config split folks are working on that in https://www.drupal.org/node/2855319 and similar issues. They would better know the answer to this question.

**Pull request merged**
