### PR TITLE
Fix infinite recursion when empty path is provided to drush_mkdir

### PR DESCRIPTION
**Pull request by njbooher**
Encountered this while trying debug an issue with site install.

### CODE REVIEW

**Comment by weitzman** [comment]
Seems like we should fix the caller.

**Comment by njbooher** [comment]
This causes segfaults depending on php settings and it took me a while to get here. I'll report the upstream error that leads to it when I find it.

**Comment by njbooher** [comment]
mtiymzaymja2njczmtg2mdcz

**Comment by greg-1-anderson** [comment]
+1 on merging this.

**Comment by weitzman** [comment]
OK. The PR currently handles empty string. Should it handle NULL?

**Comment by greg-1-anderson** [comment]
Yeah, `empty($path)` would be an improvement.

**Comment by njbooher** [comment]
empty is return true for the string '0' which is a valid folder name. I added a type check for $path and made a new pull request https://github.com/drush-ops/drush/pull/2864 since I can't seem to re-open this one or make changes to it.

**Pull request closed without merging**
