### PR TITLE
Adding composer.json support to make-convert command.

### PR DESCRIPTION
**Pull request by grasmash**

### CODE REVIEW

**Comment by grasmash** [comment]
This changes the `make-convert` command to accept a second argument that specified format. Accepted values are `yaml` and `composer.json`. This also changes the command such that it now prints the output of the conversion to stdout rather than writing to a file. This is consistent with the behavior of the make-generate command. 

This is not a complete conversion. At present, it really only supports converting project dependencies defined using either `version: x` those of `type: git`. 

Currently, it will convert this:
````
api: '2'
core: 8.x
projects:
  embed:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 26265b5437bb0f1dcb916a6a1169d53382a23646
    subdir: contrib/media
  entity_embed:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 9760c0a790bccb30d7e15815fdfa6d1794453d3a
    subdir: contrib/media
  media_entity:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: f8decb81965037b05c51ce8c16eae8c37256e7a0
    subdir: contrib/media
  media_entity_embeddable_video:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: f7e51c2cccd875e1fd09d018c11fd50c93a71507
    subdir: contrib/media
  media_entity_instagram:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 75e41cbae35f260fa0e3e76f90562e26b4dc162d
    subdir: contrib/media
  media_entity_twitter:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 179e19e159f7df2172316030fc7c110b6f0d3efd
    subdir: contrib/media
  media_entity_image:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: f17384aeba3c8c00bbc57bfa8fa68529992873ce
    subdir: contrib/media
  ctools:
    type: module
    download:
      type: git
      branch: 8.x-3.x
      revision: e27c2663027a4f90dffb39f7fd6ed8a92e5d61d4
    subdir: contrib/layout
    patch:
      - 'https://www.drupal.org/files/issues/2607594-20.patch'
  layout_plugin:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 993c829961b5b304a0094d7cd33f014edccf859e
    subdir: contrib/layout
  panels:
    type: module
    download:
      type: git
      branch: 8.x-3.x
      revision: a458d139e2e9e35c37048cb30dc682087593bd4d
    subdir: contrib/layout
  page_manager:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 3f15c87fec006e78954bb3e984cb80afeea4f5b2
    subdir: contrib/layout
  acquia_connector:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      revision: 302fc469eb860892fc90403b5d758eb50a715f77
    subdir: contrib
  metatag:
    type: module
    version: 1.0-beta3
    subdir: contrib
libraries:
  backbone.collectionView:
    type: library
    directory_name: backbone.collectionView
    download:
      type: get
      url: 'https://github.com/rotundasoftware/backbone.collectionView/archive/master.zip'
  dropzone.js:
    type: library
    directory_name: dropzone
    download:
      type: get
      url: 'https://github.com/enyo/dropzone/archive/master.zip'
  es6-promise:
    type: library
    directory_name: es6-promise
    download:
      type: get
      url: 'https://github.com/jakearchibald/es6-promise/archive/master.zip'
  jquery.appear:
    type: library
    directory_name: jquery.appear
    download:
      type: get
      url: 'https://github.com/morr/jquery.appear/archive/master.zip'
````

To this:
````
{
    "name": "Enter name here",
    "description": "Enter description here",
    "type": "project",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.drupal-composer.org"
        }
    ],
    "require": {
        "composer/installers": "^1.0.20",
        "cweagans/composer-patches": "~1.0",
        "drupal/embed": "8.0-1.0#26265b5437bb0f1dcb916a6a1169d53382a23646",
        "drupal/entity_embed": "8.0-1.0#9760c0a790bccb30d7e15815fdfa6d1794453d3a",
        "drupal/media_entity": "8.0-1.0#f8decb81965037b05c51ce8c16eae8c37256e7a0",
        "drupal/media_entity_embeddable_video": "8.0-1.0#f7e51c2cccd875e1fd09d018c11fd50c93a71507",
        "drupal/media_entity_instagram": "8.0-1.0#75e41cbae35f260fa0e3e76f90562e26b4dc162d",
        "drupal/media_entity_twitter": "8.0-1.0#179e19e159f7df2172316030fc7c110b6f0d3efd",
        "drupal/media_entity_image": "8.0-1.0#f17384aeba3c8c00bbc57bfa8fa68529992873ce",
        "drupal/ctools": "8.0-3.0#e27c2663027a4f90dffb39f7fd6ed8a92e5d61d4",
        "drupal/layout_plugin": "8.0-1.0#993c829961b5b304a0094d7cd33f014edccf859e",
        "drupal/panels": "8.0-3.0#a458d139e2e9e35c37048cb30dc682087593bd4d",
        "drupal/page_manager": "8.0-1.0#3f15c87fec006e78954bb3e984cb80afeea4f5b2",
        "drupal/acquia_connector": "8.0-1.0#302fc469eb860892fc90403b5d758eb50a715f77",
        "drupal/metatag": "1.0-beta3",
        "backbone.collectionView": "Enter correct library name and version number",
        "dropzone.js": "Enter correct library name and version number",
        "es6-promise": "Enter correct library name and version number",
        "jquery.appear": "Enter correct library name and version number",
        "drupal/core": "8.*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "installer-paths": {
            "core": [
                "type:drupal-core"
            ],
            "docroot/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "docroot/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "docroot/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "patches": {
            "drupal/ctools": {
                "Enter ctools patch #0 description here": "https://www.drupal.org/files/issues/2607594-20.patch"
            }
        }
    }
}
````

**Comment by weitzman** [comment]
also ping to @jhedstrom for review

**Comment by greg-1-anderson** [comment]
Pretty neat.  Maybe the arguments should be `drush make-convert example.make json --composer`, for consistency.  `drush make-convert example.make --composer` could imply `json`.

c.f. https://www.drupal.org/project/composer_generate. Perhaps composer-generate could just become make-generate chained to make-convert?  Or should we also support composer output from make-generate if we support composer here?

**Comment by grasmash** [comment]
Yeah. After some more thought, it might be good to switch this so that it supports backwards compatibility. E.g., conversion of composer.json to a .make or a .make.yml file. This had the advantage of not requiring us to invent any data values.

**Comment by weitzman** [comment]
Should we commit this as is or wait for some change?

**Comment by ergonlogic** [comment]
My preference would be to make the output format into an option that defaults to YAML. That would maintain backwards compatibility.

**Comment by jhedstrom** [comment]
This is great! :+1: 

I think once the backward compatibility issue is resolved, this is good to go.

**Comment by grasmash** [comment]
@todos have been address. The commands are working. I _would_ like to add test coverage, but frankly not sure when I'll be able to.

**Comment by ergonlogic** [comment]
I recently added [tests for make-lock](https://github.com/drush-ops/drush/blob/master/tests/lockMakeTest.php). It should be easy enough to integrate the source and result files from the [comment above](https://github.com/drush-ops/drush/pull/1933#issuecomment-174051544)

**Comment by grasmash** [comment]
Looks like the PHPUnit @dataprovider tag isn't working here. Possibly due to parent class. Will have to investigate.

**Comment by grasmash** [comment]
Made fixes and collapsed commits.

**Comment by grasmash** [comment]
Alright! We've got a nice little test suite and it's passing :)

**Comment by ergonlogic** [comment]
Looks good

**Pull request merged**
