### PR TITLE
Fix #4512. Drush::redispatchOptions() no longer includes shortcut options (-y)

### LINKED ISSUE #4512: Drush::redispatchOptions() no longer includes shortcut options (-y); drush deploy fails on running config:import
**Describe the bug**
Running `drush deploy -y -v` should expect to pass through the "yes" and "verbose" options to each subcommand. This will fail when sub-processes expect those inputs to be present.

**To Reproduce**
Run `drush deploy -y -v` on a site that has configuration imports to process with the config:import step.

**Expected behavior**
That `drush config:import -y` would get run in the sub-process of the deploy command.

**Actual behavior**
`drush config:import` gets run without any yes confirmation option, blocking the command from proceeding.

Note the missing options added to the sub-process commands:
```
drush deploy -y -v
 [notice] Database updates start.
 [info] Executing: /app/vendor/drush/drush/drush updatedb --no-cache-clear --uri=***--root=/app/web
>  [success] No pending updates.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --uri=*** --root=/app/web
>  [success] Cache rebuild complete.
 [success] Config import start.
 [info] Executing: /app/vendor/drush/drush/drush config:import --uri=*** --root=/app/web
>  [notice] There are no changes to import.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --uri=***--root=/app/web
>  [success] Cache rebuild complete.
 [success] Deploy hook start.
 [info] Executing: /app/vendor/drush/drush/drush deploy:hook --uri=*** --root=/app/web
>  [success] No pending deploy hooks.
```

**Workaround**
Using the long form of `--yes` does work.

```
drush deploy --yes --verbose
 [notice] Database updates start.
 [info] Executing: /app/vendor/drush/drush/drush updatedb --no-cache-clear --verbose --yes --uri=***--root=/app/web
>  [info] helper should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/10.x/commands/#specifying-the-services-file.
>  [info] Executing: /app/vendor/drush/drush/drush updatedb:status --no-entity-updates --uri=***--root=/app/web
>  [success] No pending updates.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --verbose --yes --uri=*** --root=/app/web
>  [success] Cache rebuild complete.
 [success] Config import start.
 [info] Executing: /app/vendor/drush/drush/drush config:import --verbose --yes --uri=*** --root=/app/web
>  [info] helper should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/10.x/commands/#specifying-the-services-file.
>  [notice] There are no changes to import.
 [success] Cache rebuild start.
 [info] Executing: /app/vendor/drush/drush/drush cache:rebuild --verbose --yes --uri=*** --root=/app/web
>  [success] Cache rebuild complete.
 [success] Deploy hook start.
 [info] Executing: /app/vendor/drush/drush/drush deploy:hook --verbose --yes --uri=*** --root=/app/web
>  [info] helper should have an extra.drush.services section in its composer.json. See http://docs.drush.org/en/10.x/commands/#specifying-the-services-file.
>  [success] No pending deploy hooks.
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.2
| Drupal version? | 8.9
| PHP version     | 7.3
| OS?             | Mac

**Additional information**

### PR DESCRIPTION
**Pull request by weitzman**

### CODE REVIEW

**Comment by davereid** [comment]
Confirmed this resolves it for me. Looks like we would need the same fix for 9.x as well.

**Comment by davereid** [comment]
Feels like we should add test coverage for this as well.

**Comment by greg-1-anderson** [comment]
Drush 9 isn't getting new releases at the moment. That could change, if someone wanted to be the Drush 9 maintainer. We announced 9 is EOL, though, and are only making new releases for Drush 8 and Drush 10.

**Comment by weitzman** [comment]
I enhanced our test framework for short options, and added a short option to one of our tests, so we get notified if the new code starts failing.

**Pull request merged**
