### PR TITLE
Add plumbing for equivalent updates in updatedb

### PR DESCRIPTION
**Pull request by alexpott**
Something like this will be needed when https://www.drupal.org/project/drupal/issues/3108658 lands.

### CODE REVIEW

**Comment by alexpott** [comment]
Note this will need to be backported to any Drush versions that support 10.3.x and up.

**Review by weitzman — APPROVED** [review]
LGTM. Happy to merge this once the d.o. issue lands.

**Comment by weitzman** [comment]
Will merge once this is green.

**Comment by alexpott** [comment]
Hopefully fixed it up....

**Comment by alexpott** [comment]
Now it is failing for an unrelated PHPStan error in \Drush\Drupal\Migrate\MigrateExecutable caused by Fix PHPStorm inspections (#5471)

**Comment by alexpott** [comment]
The PHPStan issue is fixed in https://github.com/drush-ops/drush/pull/6071

**Pull request merged**
