### PR TITLE
Fixes #1270: Remove redirection of STDERR to STDOUT

### LINKED ISSUE #1270: drush remote command stderr output winds up on stdout locally
I'm trying to script some stuff and I have a command (with bash variables) like so:

```
directory=$(drush @$alias drupal-directory $module)
```

I'm running a lot of remote commands, so to make it a bit quicker I'm running over persistent ssh 'Master' connections to each server involved.  The problem is that this results in a message about the connection winding up in my $directory variable.  e.g. in the following command all of the output is on stdout:

```
drush @$alias drupal-directory webform

/var/local/www/example.com/htdocs/sites/all/modules/contrib/webform
Shared connection to 1.2.3.4 closed.
```

SSH puts that output onto stderr though, and it's the local drush command that reroutes it to stderr.

Could drush be changed to not do that, and let stderr output stay on stderr?  It's then up to whatever calls drush to combine the two if that's desired.

### PR DESCRIPTION
**Pull request by thomscode**
Fixes at least part of #1270 by removing redirection of `STDERR` to `STDOUT` in `drush_backend_invoke_concurrent`

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
If you can make progress here with superficial changes, by all means continue, though.

**Comment by thomscode** [comment]
Thank you for the warning. I will continue making what progress I can, but I must admit to quickly getting over my head with the existing tangled web. I won't push too far, but will see how much progress I can make and will update/maintain my patch in a gist and use that as necessary until the rewrite is complete.

I'd be happy to help with the rewrite as I have time and appropriate expertise.

**Comment by greg-1-anderson** [comment]
You are welcome to commit whatever you want to this branch; I just wanted to warn you that the long-desired rewrite for backend might be far off, lest you spend too much time refactoring the old version.

**Comment by thomscode** [comment]
I appreciate it

**Comment by greg-1-anderson** [comment]
The master branch is now using the Symfony Process component, and no longer redirects stderr to stdout.

**Pull request closed without merging**
