### PR TITLE
D8 Run batch process during pm-enable when needed.

### PR DESCRIPTION
**Pull request by Sutharsan**
Adds batch execution to to pm-enable command.

### CODE REVIEW

**Comment by Sutharsan** [comment]
Fixes issue #3444.

**Comment by weitzman** [comment]
could we add a test that changes language, then enables locale module and devel module? would that trigger the batch?

**Comment by Sutharsan** [comment]
I'll give it a try

**Comment by Sutharsan** [comment]
The down site of this test it that is depends on the availability of ftp.drupal.org to fetch the devel module translation from.

**Comment by weitzman** [comment]
Is it feasible to put the translations in our repo (see /tests/resources) to avoid that downside?

**Comment by Sutharsan** [comment]
I've been thinking about this. It has some implications but I think it can be done by:
- Change the source of translations to local files only
- Create and using virtual file system for the translation file
- Copy a translation file from local drush test assets to the vitual translation files directory
- Change the file name pattern to not include the module version (otherwise a (different) release version of the devel module would result in a different translation file name).

**Comment by Sutharsan** [comment]
Converted the test to use a local source, and with that made it independent from an external source.

I expected Unish to use the vfStream for a virtual file system, but not. I used the drush-sut file system instead.

**Comment by weitzman** [comment]
Alas tests are failing for this and the D9 PR. Some fails look unrelated but the test added here is failing.

**Comment by Sutharsan** [comment]
It turns out that `drush php-eval` does not autoload `drush php-eval "\Drupal\language\Entity\ConfigurableLanguage::create(...)"` does not work. I've tried different variations with `require_once()` too, but in vain.

I've removed the test, as I see no way to add a language in the drupal sut. I propose to re-add this test once there is a drush `language-add`.

**Comment by weitzman** [comment]
Why would that class not autoload? Is the command not bootstrapping properly? 

In any case, we really aren't adding features to 8.x anymore so i'm fine with skipping this for 8.x if we can't get a test working.

**Comment by Sutharsan** [comment]
I don't know about the why.
Running `drush php-eval "\Drupal\language\Entity\ConfigurableLanguage::create(['id' => 'nl', 'label' => 'Dutch'])->save()"` in a drush8 + drupal8 environment _and_ in the unish test, both result in
> Fatal error: Uncaught Error: Class 'Drupal\language\Entity\ConfigurableLanguage' not found in /Users/erikstielstra/.drush/.versions/drush-8.x/commands/core/core.drush.inc(1165) : eval()'d code:1

While the same code does work as expected in Drush9 + Drupal8 and in tests.

**Comment by weitzman** [comment]
We decided not to add any features to Drush 8.

**Pull request closed without merging**
