### PR TITLE
DB prefix ignored when installing site.

### PR DESCRIPTION
**Pull request by RoSk0**

### CODE REVIEW

**Comment by RoSk0** [comment]
Test only, will add fix when test fail.

**Comment by RoSk0** [comment]
Tests failed.

Pushed fix.

**Comment by weitzman** [comment]
The fix looks good. The test only runs on postgres. Is that needed? I would think we would want a universal test ... I'd be OK with no test here if thats easier.

**Comment by RoSk0** [comment]
Hi Moshe,

I removed special test behaviour for PostgreSQL. I was too influenced by #1523 when I wrote that test.

**Comment by weitzman** [comment]
This was reverted as it caused sqlite tests to fail.

**Comment by RoSk0** [comment]
OK, traced it down to src/Sql/SqlSqlite.php::creds(). SQLite driver ignore prefix completely when it should treat as core driver, adding as suffix to the DB file name (see Drupal\Core\Database\Driver\sqlite\Connection::__construct() ).

So we cannot rely on actual table name being same across different DBs...

Question: should we remove SQLite from this test? Or should we modify test conditions for it?

**Comment by RoSk0** [comment]
Excluded SQLite from test and opened follow up #3912.

**Comment by weitzman** [comment]
Did you mean to push something here?

**Comment by RoSk0** [comment]
Hm, I did, but haven't checked that nothing changed for this PR. Created new PR #3920.

**Pull request merged**
