### PR TITLE
Restore skipped test testUpdateModuleWithServiceDependency()

### LINKED ISSUE #3737: Restore skipped test testUpdateModuleWithServiceDependency()
One of our tests requires a patch to be applied to Drupal core in order to fix a core bug that interferes with the test. We were initially applying the patch using [cweagans/composer-patches](https://github.com/cweagans/composer-patches) but this had the unintended side effect that the patch would be applied on our user's projects if a certain flag was set. The patch was removed in #3735, and also the test was disabled to we can maintain a green build for now.

The scope of this issue is to allow this test to run again.

Possible solutions:

1. The best possible solution would be to fix the bug in core and get it committed and released. The test would then be able to run on the versions of core that include the fix. Ref. [Issue #2863986: Allow updating modules with new service dependencies](https://www.drupal.org/project/drupal/issues/2863986).
2. A second possibility is to implement a new `patches-dev` feature in `composer-patches` that allows to only apply certain patches in case a development build is being created, and these patches would not propagate to depending projects. Ref. https://github.com/cweagans/composer-patches/issues/237
3. As a quick fix we could include a couple of commands in our CI pipeline to download the patch and apply it.

### PR DESCRIPTION
**Pull request by pfrenssen**
Fixes #3737

### CODE REVIEW

**Comment by weitzman** [comment]
Any chance you can enhance the test so it gets skipped if a non-patched Drupal is detected? That way tests can pass locally as well.

**Comment by pfrenssen** [comment]
I think a good way to detect it is to check whether the test module named `new_dependency_test` exists.

**Comment by pfrenssen** [comment]
I added a simple check that looks if the test module that is added by the patch exists in the filesystem.

**Comment by claudiu-cristea** [comment]
The trick looks good and fixes the problem.

**Pull request merged**
