### PR TITLE
[Backport] Add support for git repositories in the 'includes' directive.

### PR DESCRIPTION
**Pull request by pmatias**
This is a backport of https://github.com/drush-ops/drush/pull/1063 (please see PR for full documentation on the matter) for the 6.x branch. 

Mentioned PR is already reviewed, tested and merged into master. It would be great if we can do the same for the 6.x branch.

Thanks!

### CODE REVIEW

**Comment by dickolsson** [comment]
I'd say this is RTBC since the PR to `master` got committed and all tests are gereen here. :smile:

@jhedstrom Would it be possible to have a look at this? :angel:

**Comment by dickolsson** [comment]
@jhedstrom Any updates on having this backport merged?

**Comment by dickolsson** [comment]
@jhedstrom @weitzman Please let us know what we can do to help this backport getting committed :-) Should we provide more test coverage, documentation or anything else? :-)

Lots of love
dixon_

**Comment by jhedstrom** [comment]
Thanks all!

**Pull request merged**
