### PR TITLE
#2079: Fixed sql-dump command.

### LINKED ISSUE #2079: Drush command ard failing with PostgreSQL 9.5
Running drush ard command fails with on server running PostgreSQL 9.5:

`/usr/lib/postgresql/9.5/bin/pg_dump: unrecognized option '--no-align'`

Apparently the used option '--no-align' is no longer available in version 9.5 of PostgreSQL.

### PR DESCRIPTION
**Pull request by RoSk0**
Closes #2079   .

### CODE REVIEW

**Comment by RoSk0** [comment]
@cafuego According to http://docs.drush.org/en/master/install/#drupal-compatibility Drush 9 is not compatible with Drupal 7 and Drupal 8 before 8.4 so its not expected to be working in your case.
Can you please test #3268 which is the same fix for Drush 8 which still supports Drupal 7.

**Comment by RoSk0** [comment]
Rebased branch to incorporate latest changes.

**Comment by RoSk0** [comment]
Tests failing on master... :(

**Comment by cafuego** [comment]
@RoSk0 Sorry, I applied the change to drush 8.1.6, not drush 9.

I *may* have run into https://github.com/drush-ops/drush/pull/2567 again when checking, I can't remember if I updated to the latest drush 8.x-dev first (thus undoing the manual fix for https://github.com/drush-ops/drush/pull/2567) before trying 3267. I'll retry when I get a moment.

**Comment by RoSk0** [comment]
Rebased branch. Not sure what this "Shippable" is about and why is it failing...

**Comment by cafuego** [comment]
I finally got some time to test with a clean drush 8.x-dev. Both this fix and the fix on https://github.com/drush-ops/drush/pull/2282 allow me to create database dumps, so I giess it's a matter of preference as to what the preferred fix is.

Note that in my case, the bigger issue is https://github.com/drush-ops/drush/pull/2567 (which stops drush vanilla working at all)

**Comment by weitzman** [comment]
df6fba0d4a9024aa4deecbac2c36c657d4d9d806

**Pull request closed without merging**
