### PR TITLE
Use wildcard in host name in GRANT ALL PRIVILEGES

### PR DESCRIPTION
**Pull request by zaporylie**
This pull request fixes issue #1702.

I think it should be manually tested before merging.

### CODE REVIEW

**Comment by weitzman** [comment]
I generally develop with mysql root user. Hope someone else can do a some manual testing.

**Comment by zaporylie** [comment]
OK, so I've just tested it against localhost, ip address and domain name and it works:
- localhost
````
root@ff5bca1392fa:/app/drupal-8.0.0-rc2# drush si minimal --db-url=mysql://test_user4:test_password@localhost/test_database4 --db-su=root --db-su-pw=test
You are about to create a /app/drupal-8.0.0-rc2/sites/default/settings.php file and CREATE the 'test_database4' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                             [ok]
Installation complete.  User name: admin  User password: KEsYdSPfaR                                                                                                      [ok]
Congratulations, you installed Drupal!                                                                                                                                   [status]
root@ff5bca1392fa:/app/drupal-8.0.0-rc2# mysql -ptest -e "SHOW GRANTS FOR test_user4;"
+-----------------------------------------------------------------------------------------------------------+
| Grants for test_user4@%                                                                                   |
+-----------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'test_user4'@'%' IDENTIFIED BY PASSWORD '*4414E26EDED6D661B5386813EBBA95065DBC4728' |
| GRANT ALL PRIVILEGES ON `test_database4`.* TO 'test_user4'@'%'                                            |
+-----------------------------------------------------------------------------------------------------------+
````
- external IP
````
root@ff5bca1392fa:/app/drupal-8.0.0-rc2# drush si minimal --db-url=mysql://test_user3:test_password@172.17.0.17/test_database3 --db-su=root --db-su-pw=test
You are about to create a /app/drupal-8.0.0-rc2/sites/default/settings.php file and CREATE the 'test_database3' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                             [ok]
Installation complete.  User name: admin  User password: 9LSSKJy3B2                                                                                                      [ok]
Congratulations, you installed Drupal!                                                                                                                                   [status]
root@ff5bca1392fa:/app/drupal-8.0.0-rc2# mysql -hmysql4 -ptest -e "SHOW GRANTS FOR test_user3;"
+-----------------------------------------------------------------------------------------------------------+
| Grants for test_user3@%                                                                                   |
+-----------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'test_user3'@'%' IDENTIFIED BY PASSWORD '*4414E26EDED6D661B5386813EBBA95065DBC4728' |
| GRANT ALL PRIVILEGES ON `test_database3`.* TO 'test_user3'@'%'                                            |
+-----------------------------------------------------------------------------------------------------------+
````
- domain name:
````
root@ff5bca1392fa:/app/drupal-8.0.0-rc2# drush si minimal --db-url=mysql://test_user2:test_password@mysql4/test_database2 --db-su=root --db-su-pw=test
You are about to create a /app/drupal-8.0.0-rc2/sites/default/settings.php file and CREATE the 'test_database2' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                             [ok]
Installation complete.  User name: admin  User password: sba5dsxSor                                                                                                      [ok]
Congratulations, you installed Drupal!   
root@ff5bca1392fa:/app/drupal-8.0.0-rc2# mysql -hmysql4 -ptest -e "SHOW GRANTS FOR test_user2;"
+-----------------------------------------------------------------------------------------------------------+
| Grants for test_user2@%                                                                                   |
+-----------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'test_user2'@'%' IDENTIFIED BY PASSWORD '*4414E26EDED6D661B5386813EBBA95065DBC4728' |
| GRANT ALL PRIVILEGES ON `test_database2`.* TO 'test_user2'@'%'                                            |
+-----------------------------------------------------------------------------------------------------------+
````

**Comment by zaporylie** [comment]
And output for current HEAD:
````
root@26deedd67c33:/app/drupal-8.0.0-rc2# mysql -hmysql4 -ptest -e "SHOW DATABASES;"
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test_database2     |
| test_database3     |
+--------------------+
root@26deedd67c33:/app/drupal-8.0.0-rc2# drush si minimal --db-url=mysql://test_user4:test_password@mysql4/test_database4 --db-su=root --db-su-pw=test -y
You are about to create a /app/drupal-8.0.0-rc2/sites/default/settings.php file and CREATE the 'test_database4' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                             [ok]
exception 'Drupal\Core\Installer\Exception\InstallerException' with message 'Resolve all issues below to continue the installation. For help configuring your database   [error]
server, see the <a href="https://www.drupal.org/getting-started/install">installation handbook</a>, or contact your hosting provider.<div
class="item-list"><ul><li>Failed to connect to your database server. The server reports the following message: <em class="placeholder">SQLSTATE[28000] [1045] Access
denied for user &#039;test_user4&#039;@&#039;172.17.0.19&#039; (using password: YES)</em>.<ul><li>Is the database server running?</li><li>Does the database exist or does
the database user have sufficient privileges to create the database?</li><li>Have you entered the correct database name?</li><li>Have you entered the correct username
and password?</li><li>Have you entered the correct database hostname?</li></ul></li></ul></div>' in /app/drupal-8.0.0-rc2/core/includes/install.core.inc:896
Stack trace:
#0 /app/drupal-8.0.0-rc2/core/includes/install.core.inc(567): install_get_form('Drupal\Core\Ins...', Array)
#1 /app/drupal-8.0.0-rc2/core/includes/install.core.inc(523): install_run_task(Array, Array)
#2 /app/drupal-8.0.0-rc2/core/includes/install.core.inc(115): install_run_tasks(Array)
#3 /root/.composer/vendor/drush/drush/includes/drush.inc(721): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#4 /root/.composer/vendor/drush/drush/includes/drush.inc(706): drush_call_user_func_array('install_drupal', Array)
#5 /root/.composer/vendor/drush/drush/commands/core/drupal/site_install.inc(78): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#6 /root/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(289): drush_core_site_install_version('minimal', Array)
#7 [internal function]: drush_core_site_install('minimal')
#8 /root/.composer/vendor/drush/drush/includes/command.inc(364): call_user_func_array('drush_core_site...', Array)
#9 /root/.composer/vendor/drush/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#10 [internal function]: drush_command('minimal')
#11 /root/.composer/vendor/drush/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#12 /root/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#13 /root/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#14 /root/.composer/vendor/drush/drush/drush.php(11): drush_main()
#15 {main}
root@26deedd67c33:/app/drupal-8.0.0-rc2# mysql -hmysql4 -ptest -e "SHOW DATABASES;"
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test_database2     |
| test_database3     |
| test_database4     |
+--------------------+
````

**Comment by weitzman** [comment]
Merged. Thanks for the PR and the testing.

**Pull request merged**
