### PR TITLE
WIP: Add recursion detection to RedispatchToSiteLocal

### PR DESCRIPTION
**Pull request by webflo**
Add recursion detection to RedispatchToSiteLocal to mitigate faulty configurations with site-local Drush.

Related to https://github.com/webflo/drupal-finder/issues/34

### CODE REVIEW

**Comment by webflo** [comment]
I think the fix is necessary because the logic in ``::redispatchIfSiteLocalDrush`` and ``::findSiteLocalDrush`` is not bullet proof again wrong configurations. Here is one example (https://gist.github.com/webflo/fe2105bf0ebbd22f234e4ea12e867ba2) how the whole setup blows if people convert their site from default drupal layout to drupal-project and don't cleanup everything properly.

Drush picks up ``../vendor/drush/drush/drush`` as site-local Drush even if this composer autoloader is not used in the Drupal installation.

**Comment by greg-1-anderson** [comment]
The recursion limit here should be one -- Drush should never redispatch to a site-local Drush after it has already redispatched to a site-local Drush. You might get two exec's if there is a finder/launcher starting things off, but ideally Drush should always get the redispatch right on the first try.

Drush allows us to pass the vendor directory in as an environment variable. Maybe we should always do this if there is a site-local redispatch, and never redispatch again if this environment variable has been set.

Regarding confusion over whether the vendor directory is part of the current site or not, do we need to examine Drupal's `__ROOT__/autoload.php` to do this correctly? I'd rather not have to parse this file, but I'm not sure how to detect if `__ROOT__/../vendor` is not part of the Drupal site.

**Comment by webflo** [comment]
Getting from ``autoload.php`` back to the vendor folder is in general very hard and error prone. Because composer does not provide the metadata, because it should not matter on runtime. ``drupal-finder`` does various things but avoids parsing/loading the ``autoload.php`` (see https://github.com/webflo/drupal-finder/blob/master/src/DrupalFinder.php#L88).

I think its better to keep current code the complexity is already very high. It not possible to support every configuration and especially if its broken or misconfigured.

**Comment by webflo** [comment]
Decreasing the limit is a good idea. Maybe we could display a log message if drush is invoked with ``--debug``. Currently its not possible to see that redispatching is happening.

**Comment by segi** [comment]
I was on of person who reported the infinite loop problem. In my situation and other fix would have been enough. 
If we add realpath() here like:
``` php
// If the site-local Drush is us, then we do not need to redispatch.
if (Path::isBasePath(realpath($vendor), realpath($siteLocalDrush))) {
  return false;
}
```
but maybe this solution is more general and it can prevent more problem.

**Comment by weitzman** [comment]
I agree that it would be good to log a message when we redispatch. We can't right now, as the logger is not available yet. We should fix this ASAP. Would it be ok to just write to stderr for now?

**Comment by greg-1-anderson** [comment]
Ideally we would like to log preflight messages in `--debug` mode, and do nothing when debug is not set. At the moment, `--debug` isn't captured by preflight args. We could set debug in preflight args, and then maybe create a PreflightLog class that writes to stderr iff in debug mode. We could manually inject PreflightLog into RedispatchToSiteLocal.

I would say that PreflightLog should not be derived from psr/log.

**Comment by jurgenhaas** [comment]
@weitzman thanks for referring me over from #3143 - I was having a look and it sounds that my issue is similar to what @segi describes. Using realpath() is what I assumed to be the correct way forward as well, when I analysed my other issue. What kind of help is required here to move this forward?

**Comment by weitzman** [comment]
Added a logger per @greg-1-anderson  mini spec - https://github.com/drush-ops/drush/pull/3154

**Comment by grasmash** [comment]
This issue is a blocker for one of our products. In our case, merging #3235 is sufficient to resolve the issue, as @segi indicated.

**Comment by weitzman** [comment]
#3235 fixed this i think

**Comment by LichP** [comment]
I came across this issue while experiencing a drush recursion which was due to a symlinked vendor folder. I'm using a current version of drush with #3235 applied - in my case applying the fix from @segi 's comment above resolved the problem. This use case is pretty niche so probably doesn't warrant reopening this issue - just posting this for reference.

**Pull request closed without merging**
