### PR TITLE
Add locale-check and locale-update commands (#1817)

### PR DESCRIPTION
**Pull request by tstoeckler**
See #1817

### CODE REVIEW

**Comment by damiankloip** [comment]
This is looking pretty good. The fact that there is not something at the API level in D8 is kind of crazy...

**Comment by tstoeckler** [comment]
Thanks!

Yes, I agree completely. It's totally crazy. But IMHO all the more reason to have this in Drush, because you can't just do
```bash
drush ev "\Drupal::service('locale.updater')->update();"
```
or similar as a temporary shiv, because something like that simply doesn't exist.

**Comment by weitzman** [comment]
If these are for D8+, we should rename the file with an 8 as suffix like the views8.drush.inc file.

Is there an issue to move this logic to an API function. I'd like for a Drupal patch to exist so I have a hope of not maintaining this forever.

**Comment by tstoeckler** [comment]
Opened https://www.drupal.org/node/2631584 on Drupal.org for that, added @todo's and renamed the file.

**Comment by weitzman** [comment]
Looks good. Feel free to merge this.

**Comment by tstoeckler** [comment]
Totally failed at Git as I just realized. Now actually added @todo's et al.

Thanks for the endorsement, it will be great to have this for multilingual workflows. Looking forward to it

**Comment by tstoeckler** [comment]
From #1817:
> @tstoeckler will merge the PR (#1818) when he has a chance. no need to keep this issue open.
I don't have write access...

**Comment by weitzman** [comment]
Woops - my bad. I thought I had done that. Now invited.

**Comment by tstoeckler** [comment]
Yay, thanks!

**Pull request merged**
