### PR TITLE
Make batch operations report % complete while performing.

### PR DESCRIPTION
**Pull request by TracKer**
Here is another patch which will show progress for batch operations for D6, D7, and D8.
Previous pull request and small discussion located here: #1482

### CODE REVIEW

**Comment by TracKer** [comment]
Just for the information, this patch is oriented to adding progress indication on multistep batch operations. Curently it looks like this:

````
Performed update: some_module_update_7041
Performed update: some_module_update_7042
Performed update: some_module_update_7042
Performed update: some_module_update_7042
Performed update: some_module_update_7042
````

The patch make it look like this:

````
Performed update: some_module_update_7041
Performed update: some_module_update_7042 - 25% (100/400)
Performed update: some_module_update_7042 - 50% (200/400)
Performed update: some_module_update_7042 - 75% (300/400)
Performed update: some_module_update_7042 - 100% (400/400)
````

**Comment by heddn** [comment]
We are considering relying on this feature set here over in https://www.drupal.org/project/migrate_tools/issues/2701121. Where is it at? What is needed to see this land?

**Comment by weitzman** [comment]
The feature looks useful. So a reroll for Drush 9 is encouraged.

**Comment by greg-1-anderson** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
