### PR TITLE
Fix container rebuilds on deployment identifier change

### PR DESCRIPTION
**Pull request by alexpott**
This fixes the most recent error described on https://www.drupal.org/project/drupal/issues/2985199 (see comment 70)

### CODE REVIEW

**Comment by weitzman** [comment]
thanks @dpagini and @alexpott for the fix.

**Comment by dpagini** [comment]
Thank YOU @weitzman and @alexpott for your help with this one, it was super tricky!

**Comment by awm086** [comment]
I know this is closed but I am experiencing this issue after upgrading to 9.2. should I create an issue or is it tracked?

**Comment by njt1982** [comment]
Just for reference (in case this come up in Google!).... This patch also fixed an error where a `drush deploy` broke the container cache so this error happened

    Module XXXX has an entry in the system.schema key/value storage, but is not installed.

If I did `drush cr` everything was fine, but it seemed that `drush cim` triggered this error.

I was using Drush 10.3.6 and cannot currently upgrade past this due to the migrate_tools 5.x restrictions.

**Pull request merged**
