### PR TITLE
Test coverage for Updatedb exits with 0 if TypeError occurs

### LINKED ISSUE #3376: When an update fails, updatedb is still exiting with 0
This looks like a regression from #3095.

In attempting to run updates from a Drupal 8.4.4 install to 8.5.x using Drush 9.1.0, a fatal error is thrown, but drush still returned success. Note the last line with the exit code:

```
-------- ------------- --------------- --------------------------------------- 
  Module   Update ID     Type            Description                            
 -------- ------------- --------------- --------------------------------------- 
  system   8501          hook_update_n   Add the 'revision_default' field to    
                                         all relevant entity types.             
  views    8500          hook_update_n   Update field names for multi-value     
                                         base fields.                           
  system   change_acti   post-update     Change plugin IDs of actions.          
           on_plugins                                                           
  system   field_forma   post-update     Clear caches due to schema changes in  
           tter_entity                   core.entity.schema.yml.                
           _schema                                                              
  views    bulk_field_   post-update     Update dependencies for moved bulk     
           moved                         field plugin.                          
  views    entity_link   post-update     Add additional settings to the entity  
           _url                          link field and convert node_path       
                                         usage  to entity_link.                 
  views    filter_plac   post-update     Add placeholder settings to string or  
           eholder_tex                   numeric filters.                       
           t                                                                    
 -------- ------------- --------------- --------------------------------------- 

 // Do you wish to run the specified pending updates?: yes.                     

 [notice] Update started: system_update_8501
TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php).
 [error]  TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php) #0 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/lib/Drupal/Component/Annotation/Plugin/Discovery/AnnotatedClassDiscovery.php(113): Doctrine\Common\Annotations\AnnotationRegistry::reset()
#1 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php(106): Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery->getDefinitions()
#2 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/lib/Drupal/Core/Plugin/DefaultPluginManager.php(175): Drupal\Core\Entity\EntityTypeManager->findDefinitions()
#3 /srv/bindings/221f215df214430b82daa4e29943f72b/code/web/core/modules/system/system.install(2079): Drupal\Core\Plugin\DefaultPluginManager->getDefinitions()
#4 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(185): system_update_8501(Array)
#5 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/includes/batch.inc(235): Drush\Commands\core\UpdateDBCommands->updateDoOne('system', 8501, Array, Object(DrushBatchContext))
#6 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/includes/batch.inc(183): _drush_batch_worker()
#7 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/includes/batch.inc(95): _drush_batch_command('2')
#8 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Commands/core/UpdateDBCommands.php(142): drush_batch_command('2')
#9 [internal function]: Drush\Commands\core\UpdateDBCommands->process('2', Array)
#10 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#11 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#12 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#13 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Command/Command.php(252): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\LessStrictArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#20 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/drush.php(64): Drush\Runtime\Runtime->run(Array)
#21 /srv/bindings/221f215df214430b82daa4e29943f72b/code/vendor/drush/drush/drush(4): require('/srv/bindings/2...')
#22 {main}. 
 [error]  Drush command terminated abnormally due to an unrecoverable error. 
 [success] Finished performing updates.
 [notice] Command: test-85x.ci-9 -- drush updatedb [Exit: 0]
```

### PR DESCRIPTION
**Pull request by pfrenssen**
Fixes #3376

### CODE REVIEW

**Comment by pfrenssen** [comment]
Started working on test coverage, this is completely untested so far.

**Comment by pfrenssen** [comment]
I have an initial test but one of the builds seems to time out, this happened on several runs. Is this a known issue on CircleCI?

https://circleci.com/gh/drush-ops/drush/1913?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

"Too long with no output (exceeded 10m0s)"

**Comment by weitzman** [comment]
I havent seen that.

maybe add -vvv to that unish.phpunit.step in .circle/config.yml. Also try
to add a timeout: directive to that step so you can let it keep working if
that's really the problem.

**Comment by pfrenssen** [comment]
Thanks for the suggestions!

**Comment by weitzman** [comment]
The underlying bug was fixed in #3376 but this test coverge would still be welcome.

**Comment by pfrenssen** [comment]
Merged in latest master, let's see how it fares now. Assigning to me, I have been granted some time to work on this next week.

**Comment by pfrenssen** [comment]
Nice, the tests are not timing out any more, so this is no longer blocked.

The tests are now passing on PHP 7 but not on PHP 5. The fatal error regarding the undefined function call cannot be caught on PHP 5.

How should we proceed with this? Since PHP 5.6 will be EOL in 3 months I don't know whether it will be even worth the effort to spend time in attempting to work around this with some code gymnastics.

Do we have a way of skipping tests on PHP5 using tags or annotations?

**Comment by weitzman** [comment]
Agree its not worthwhile to do futher gymnastics.

Here is what I suggest:

```
if ($php <= 5) {
      $this->markTestSkipped('PHP no longer tested for error handling');
}
```

**Comment by pfrenssen** [comment]
I intend to rebase this PR once the tests are green to clean up the history. I'll add the "ready to review" label once this is ready for review + merge.

**Comment by pfrenssen** [comment]
Test is green! Going to rebase on the latest master.

**Comment by weitzman** [comment]
Thanks for ensuring the long term quality of Drush, @pfrenssen.

**Comment by pfrenssen** [comment]
Thanks!

**Pull request merged**
