### PR TITLE
Fix #4494. Remove --post-update option from UpdateDB

### LINKED ISSUE #4494: drush updb does not clear caches if there are no post updates
**Describe the bug**

It looks like drush updb was optimized to only run a cache clear between updates and post updates if there are post updates and were updates.

If there are only updates that doesn't seem to happen.

That is becoming a more serious issue due to the Update cache backend that is now in core, that ignores cache writes, and for example the cached config storage only writes to cache and doesn't delete.

**To Reproduce**
Check value of config with drush cget. Run an update that changes that config value. Check again with drush cget. 

**Expected behavior**
New value is visible.

**Actual behavior**
The old value is still there.

**Workaround**
drush cr

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.x/9.x
| Drupal version? | 8.x
| PHP version     | 7.x,5.x
| OS?             | Mac/Linux/Windows

**Additional information**

### PR DESCRIPTION
**Pull request by weitzman**
Per https://github.com/drush-ops/drush/issues/4494#issuecomment-1503165344

### CODE REVIEW

**Comment by weitzman** [comment]
deploy command does suppresses any cache clears within updatedb and does an unconditional clear after updates and before config import. If we remove --no-cache-clear we will do two in a row in any deploy where there are updates. how should we handle this @alexpott? See https://github.com/drush-ops/drush/blob/de82698455ac0a88c050555f9ef904cafccbf120/src/Commands/core/DeployCommands.php#L33-L47

**Comment by alexpott** [comment]
I think we should remove the first `$this->cacheRebuild($manager, $self, $redispatchOptions); ` from deploy. Calling updatedb from drush should always result in a cache clear even if there are no updates.

**Comment by weitzman** [comment]
I implemented the unified cache clear from updatedb, which happends regardless of whether there were pending updates/post-updates or not.

I'm still a little hesitant to get rid of the --no-cache-clear option. That went in with #308. How sympathetic are folks to that request? Maybe these folks should call updatedb:status and avoid clearing if there is nothing to do?

**Comment by greg-1-anderson** [comment]
Skipping cache clears is definitely a "no seatbelts" option. Folks who use this are implicitly promising to clear the cache later. There are a lot of things you can do to a Drupal site that cause the cache to become dirty, so I don't think this option is too sharp. Being able to speed up sequential operations in CI is compelling, though, so it seems desirable to maintain that capability.

**Comment by weitzman** [comment]
OK, --no-cache-clear is back in, and deploy command no longer uses it since updatedb clears by default.

**Pull request merged**
