### PR TITLE
Prevent drush from crushing, when command extends non-existent class

### LINKED ISSUE #5860: Prevent drush from crushing, when module's command extends non-existent class
**Describe the bug**
I'm trying to update from D9 to D10 and to Drush 12.4.3. Along with core update I have to update [path_redirect_import](https://www.drupal.org/project/path_redirect_import) module from 1 to 2 version. Version 1 of this module has following [dependencies](https://git.drupalcode.org/project/path_redirect_import/-/blob/8.x-1.0-beta5/path_redirect_import.info.yml?ref_type=tags#L7-L8) and version 2 has [couple of new ones](https://git.drupalcode.org/project/path_redirect_import/-/blob/2.0.x/path_redirect_import.info.yml?ref_type=heads#L7-L10). But the problem is that old version has drush command, extending [DrushCommands](https://git.drupalcode.org/project/path_redirect_import/-/blob/8.x-1.0-beta5/src/Commands/PathRedirectImport.php?ref_type=tags#L15) class and new version's command extends [MigrateToolsCommand](https://git.drupalcode.org/project/path_redirect_import/-/blob/2.0.x/src/Drush/Commands/PathRedirectImportCommands.php?ref_type=heads#L30). On D9 version of the site, which I'm trying to update, migrate_tools module is not enabled and thus system is not aware of its drush command representing class.

**To Reproduce**
Install site on D9 and Drush 10. Install path_redirect_import module 1st version. Update code to D10, Drush 12 and path_redirect_import to 2. Try to execute any drush command.

**Expected behavior**
Drush skips such cases without crushing.

**Actual behavior**
Drush fails with following error:

```bash
Error: Class "Drupal\migrate_tools\Drush\Commands\MigrateToolsCommands" not found in /var/www/html/web/modules/contrib/path_redirect_import/src/Drush/Commands/PathRedirectImportCommands.php on line 30 #0 /var/www/html/vendor/composer/ClassLoader.php(576): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/html/vendor/drush/drush/src/Runtime/LegacyServiceInstantiator.php(199): ReflectionClass->__construct()
#4 /var/www/html/vendor/drush/drush/src/Runtime/LegacyServiceInstantiator.php(177): Drush\Runtime\LegacyServiceInstantiator->instantiateObject()
#5 /var/www/html/vendor/drush/drush/src/Runtime/LegacyServiceInstantiator.php(128): Drush\Runtime\LegacyServiceInstantiator->create()
#6 /var/www/html/vendor/drush/drush/src/Runtime/LegacyServiceInstantiator.php(60): Drush\Runtime\LegacyServiceInstantiator->instantiateServices()
#7 /var/www/html/vendor/drush/drush/src/Boot/DrupalBoot8.php(257): Drush\Runtime\LegacyServiceInstantiator->loadServiceFiles()
#8 /var/www/html/vendor/drush/drush/src/Boot/DrupalBoot8.php(233): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands()
#9 /var/www/html/vendor/drush/drush/src/Boot/BootstrapManager.php(236): Drush\Boot\DrupalBoot8->bootstrapDrupalFull()
#10 /var/www/html/vendor/drush/drush/src/Boot/BootstrapManager.php(422): Drush\Boot\BootstrapManager->doBootstrap()
#11 /var/www/html/vendor/drush/drush/src/Boot/BootstrapManager.php(357): Drush\Boot\BootstrapManager->bootstrapMax()
#12 /var/www/html/vendor/drush/drush/src/Boot/BootstrapManager.php(329): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex()
#13 /var/www/html/vendor/drush/drush/src/Boot/BootstrapHook.php(36): Drush\Boot\BootstrapManager->bootstrapToPhase()
#14 /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(44): Drush\Boot\BootstrapHook->initialize()
#15 /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook()
#16 /var/www/html/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook()
#17 /var/www/html/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize()
#18 /var/www/html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(376): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(292): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize()
#20 /var/www/html/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#22 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#23 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#24 /var/www/html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#25 /var/www/html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#26 /var/www/html/vendor/drush/drush/drush(4): require('...')
#27 /var/www/html/vendor/bin/drush(119): include('...')
#28 {main}
```

**Workaround**
Of course, we can enable needed modules before deployment, but I think, it is helpful for automated deployment to have Drush expecting such cases.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.4.3
| Drupal version? | 10.2.2
| PHP version     | 8.3
| OS?             | Linux

**Additional information**
Found this [PR](https://github.com/drush-ops/drush/pull/5656), which adds try/catch, but in my case this check needs to be added in other places, where `new \ReflectionClass($class)` is used

### PR DESCRIPTION
**Pull request by ilyano**
Fixes #5860

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
We probably need some form of notification, even if it's only a debug log message, so that commands do not silently disappear when underlying things change in such a way as to prevent instantiation from working.

**Comment by ilyano** [comment]
@greg-1-anderson thanks for the notice! I've added debug message.

**Comment by greg-1-anderson** [comment]
This seems ok to me, but it needs to target the 13.x branch now.

**Comment by ilyano** [comment]
@greg-1-anderson target branch has been updated, source branch has been rebased.

**Review by greg-1-anderson — APPROVED** [review]
LGTM

**Pull request merged**
