### PR TITLE
Add phpstan baseline and bump to level 2

### PR DESCRIPTION
**Pull request by weitzman**
```
 ------ ------------------------------------------------------------------------------------------------ 
  Line   Commands/ConfiguresPrompts.php (in context of class Drush\Commands\DrushCommands)               
 ------ ------------------------------------------------------------------------------------------------ 
  51     Call to an undefined method Symfony\Component\Console\Style\SymfonyStyle::secret().             
         ✏️  Commands/ConfiguresPrompts.php                                                              
  91     Call to an undefined method Symfony\Component\Console\Style\SymfonyStyle::askWithCompletion().  
         ✏️  Commands/ConfiguresPrompts.php                                                              
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------ 
  Line   Commands/core/MigrateRunnerCommands.php                                       
 ------ ------------------------------------------------------------------------------ 
  391    Call to an undefined method Drupal\migrate\Plugin\MigrationInterface::set().  
         ✏️  Commands/core/MigrateRunnerCommands.php                                   
 ------ ------------------------------------------------------------------------------ 

 ------ ----------------------------------------------------------------- 
  Line   Commands/core/SiteInstallCommands.php                            
 ------ ----------------------------------------------------------------- 
  305    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/core/SiteInstallCommands.php                        
  311    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/core/SiteInstallCommands.php                        
  318    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/core/SiteInstallCommands.php                        
  325    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/core/SiteInstallCommands.php                        
  332    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/core/SiteInstallCommands.php                        
  339    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/core/SiteInstallCommands.php                        
 ------ ----------------------------------------------------------------- 

 ------ ----------------------------------------------------------------- 
  Line   Commands/field/FieldBaseOverrideCreateCommands.php               
 ------ ----------------------------------------------------------------- 
  154    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/field/FieldBaseOverrideCreateCommands.php           
  159    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/field/FieldBaseOverrideCreateCommands.php           
 ------ ----------------------------------------------------------------- 

 ------ ----------------------------------------------------------------- 
  Line   Commands/field/FieldCreateCommands.php                           
 ------ ----------------------------------------------------------------- 
  283    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/field/FieldCreateCommands.php                       
  305    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/field/FieldCreateCommands.php                       
  310    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/field/FieldCreateCommands.php                       
  394    Result of method Drush\Style\DrushStyle::text() (void) is used.  
         ✏️  Commands/field/FieldCreateCommands.php                       
 ------ ----------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   Drupal/DrupalKernelTrait.php (in context of class Drush\Drupal\DrupalKernel)                    
 ------ ------------------------------------------------------------------------------------------------ 
  79     Call to an undefined method Drupal\Core\DependencyInjection\ServiceModifierInterface::check().  
         ✏️  Drupal/DrupalKernelTrait.php                                                                
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   Drupal/DrupalKernelTrait.php (in context of class Drush\Drupal\InstallerKernel)                 
 ------ ------------------------------------------------------------------------------------------------ 
  79     Call to an undefined method Drupal\Core\DependencyInjection\ServiceModifierInterface::check().  
         ✏️  Drupal/DrupalKernelTrait.php                                                                
 ------ ------------------------------------------------------------------------------------------------ 

 ------ ------------------------------------------------------------------------------------------------ 
  Line   Drupal/DrupalKernelTrait.php (in context of class Drush\Drupal\UpdateKernel)                    
 ------ ------------------------------------------------------------------------------------------------ 
  79     Call to an undefined method Drupal\Core\DependencyInjection\ServiceModifierInterface::check().  
         ✏️  Drupal/DrupalKernelTrait.php                                                                
 ------ ------------------------------------------------------------------------------------------------ 

 [ERROR] Found 18 errors                                                                                                


```

### CODE REVIEW

**Comment by DieterHolvoet** [comment]
> Result of method Drush\Style\DrushStyle::text() (void) is used.

Seems to be the result of the todo added to `DrushStyle::text()`:

> @todo return type of parent has changed

**Comment by DieterHolvoet** [comment]
>  Result of method Drush\Style\DrushStyle::text() (void) is used.

This is the result of https://github.com/drush-ops/drush/pull/5823. Usage of the `ask()` method was replaced with `text()`, even though `text()` is supposed to be used for outputting text, not collecting text. I propose switching back to `ask()`.

>  Call to an undefined method Drupal\Core\Entity\EntityInterface::setComponent().

I propose adding the following before the `setComponent()` call: `assert($storage instanceof EntityDisplayInterface)`

> Call to an undefined method Drupal\Core\Field\FieldStorageDefinitionInterface::isLocked().
> Call to an undefined method Drupal\Core\Field\FieldStorageDefinitionInterface::getBundles().
> Call to an undefined method Drupal\Core\Field\FieldStorageDefinitionInterface::delete().

I think it's safe to add an assert here as well: `assert($fieldStorage instanceof FieldStorageConfigInterface);`

**Comment by weitzman** [comment]
Thanks for the assert() idea. I'll use that for a lot of fixes here.

> Usage of the ask() method was replaced with text(), even though text() is supposed to be used for outputting text, not collecting text. I propose switching back to ask()

I agree, but we want pretty prompts and [Laravel Prompts chose to use text() for text input instead of ask()](https://laravel.com/docs/10.x/prompts#text). I think we should keep following their lead.

**Comment by DieterHolvoet** [comment]
Well, we kinda have to follow `StyleInterface` here right? I would stick to `ask()` and call Laravel's `text()` in `DrushStyle::ask()`. The text methods do different things in Symfony and Laravel, so not much we can do there.

**Comment by weitzman** [comment]
Merged without fixing the items in the description. Lets tackle those in new PRs.

**Pull request merged**
