### PR TITLE
Fix PHP 8.1 - allow empty yaml

### PR DESCRIPTION
**Pull request by andypost**
One more fix for 10.x after  https://github.com/drush-ops/drush/pull/4840

It also needs https://github.com/consolidation/site-alias/pull/44

PS: 8.x branch is different https://github.com/drush-ops/drush/pull/4839

### CODE REVIEW

**Comment by weitzman** [comment]
This is needed on 11.x also, right?

**Comment by andypost** [comment]
Yes, just did not check on 11

**Comment by weitzman** [comment]
Cherry picked to 11.x as well. Thanks.

**Comment by andypost** [comment]
Thank you, I did not check gh-workflows but I bet it needs to add 8.1 to prevent regressions in future

**Comment by weitzman** [comment]
Good idea. See https://github.com/drush-ops/drush/pull/4846

**Pull request merged**
