### PR TITLE
Workaround for removed drupal bootstrap constants.

### PR DESCRIPTION
**Pull request by Berdir**
I guess it needs more refactoring, but for now, I just switched to use the drush constants and cleaned it up, because nothing was calling it with anything else but configuration or full. Also nothing uses the return value.

Not sure what a proper fix would look like...

### CODE REVIEW

**Comment by Berdir** [comment]
Ah, maybe the boot() call needs to move to full as well, lets see what travis has to say :)

**Comment by jhedstrom** [comment]
This gets drush working again with the latest HEAD. Since these drush-specific constants already exist, this seems like a reasonable fix for the time being.

**Comment by pfrenssen** [comment]
It's working well for me too.

**Comment by geerlingguy** [comment]
Ha! I just ran into this error (pasting below so Google searches might help the few people getting the error) on drupal 8 head + drush head... then ran updates again and the error went away. Nice!

```
Use of undefined constant DRUPAL_BOOTSTRAP_CONFIGURATION - assumed 'DRUPAL_BOOTSTRAP_CONFIGURATION'
```

**Pull request merged**
