### PR TITLE
Use --uri from commandline over uri in an alias

### PR DESCRIPTION
**Pull request by greg-1-anderson**
This is a start, but it looks like there are a few failures in the functional tests.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
The tests like to insert `--uri=dev` by default, even if no one asked for that, for historical reasons. With this PR, that addition becomes significant, which broke some tests.

I think that the most recent commit gets us down to about one remaining failure.

**Comment by greg-1-anderson** [comment]
Somewhat related to https://github.com/drush-ops/drush/issues/3968

**Comment by weitzman** [comment]
The way to do this today is:

Old: `drush --uri=http://example.com`
New: `DRUSH_OPTIONS_URI=http://example.com drush ...`

**Comment by greg-1-anderson** [comment]
`DRUSH_OPTIONS_URI` is a decent workaround (it does work fine today), but `--uri` on the commandline has better DX and is familiar. There's no downside to making the enhancement to take `--uri` from the commandline.

**Comment by weitzman** [comment]
LGTM. Please close any other related issues that are still open,

**Pull request merged**
