### PR TITLE
Get SVN back working again

### PR DESCRIPTION
**Pull request by AdamPS**
OK, I'm not an expert on drush, nor github.  However not many people are using SVN, so I guess if I want it to work, I'm going to have to give it a try.  Sorry for any mistakes.  I would appreciate some sort of comment even if it's "thanks I'll look in a few weeks when I have time" or "thanks, but you've done it all wrong because..."

1) Main SVN fix in #1056:
- I noted the new wget package update code simply overwrites the whole old package with the new, with no fancy recursive preserving of control files, orphan dir handling etc.
- Actually that's not a big problem as in modern SVN (and I think BZR as best I could tell from a search) the control files are only at the root.
- So firstly a quick extra call to skip control files when updating drupal core.
- Secondly, set the option to drupal_move_dir to make sure we actually do overwrite.

2) The rollback part #2015 should be simple and clear.

3) #2020 is not essential to make SVN work, but will help stop it breaking in future.  I've removed various hard-coded if tests on VCS system, so there is much greater commonality of code.  I can take this one out of the pull request if needs be.

4) In passing I removed some old code/comments relating to CVS.

### CODE REVIEW

**Comment by weitzman** [comment]
Code looks OK Needs review and merge by @jonhattan

**Comment by AdamPS** [comment]
10 months later, unfortunately this seems to have stalled out!

I would really appreciate if this could be merged.  I feel that I was encouraged to contribute because no one else was really interested in the pm area.  So I took the time to learn drush and try and help out.  At the moment I have to keep merging my patches into the latest drush - which for someone who doesn't really use git gets increasingly complicated the longer it goes on:-)

I have a second pull request #2083 based on this one that solves two more long-standing drush bugs.  I feel it would be even better to commit that one.  However, the maintainers have not commented on that PR yet.

**Comment by weitzman** [comment]
alas, it seems that jonhattan never found time to review this. 

svn and bzr engines are scheduled for removal in drush9. sorry, but this will not be merged.

**Comment by AdamPS** [comment]
@weitzman OK we can lose the SVN part, but 99% of the code in this PR and the referenced one is not specific to SVN.

In fact 3 of my commits are to remove outdated code, so that should actually help in removing SVN.

**Pull request closed without merging**
