### PR TITLE
drush.launcher fix for Windows

### PR DESCRIPTION
**Pull request by mikeker**
Followup to #1673: Quoting `$found_script` handles spaces in the path. Also does a poor-man's `_drush_convert_path()` so we don't have to include any other files in the finder.

I ran into an odd problem when using drush.launcher -- without specifying that this is to run in the shell, Windows would try to have me associate the .launcher extension with a program. (And would helpfully pull up the "Search the Windows Store" dialog...  Ha!) I don't know if the correct solution is to rename the drush.launcher to something else on Windows or to use the change in this PR. Feedback appreciated!

### CODE REVIEW

**Comment by ivanjaros** [comment]
Yep, just updated drush so I can work with D8RC1 and am getting the same thing on Win10.

**Comment by weitzman** [comment]
Hard coding sh like that is wrong for non Windows. It bypasses the shebang line at top of launcher.

**Comment by mikeker** [comment]
I figured that was the case. I assume we don't want to drag
drush_is_windows into startup.inc.

I'll look into how best to deal with the association on the Windows side of
things.

**Comment by mikeker** [comment]
I've tried a few ways of associating the .launcher file with `sh` on Windows 10 but all of them seem to lose the argument list in the process (so `drush status --verbose` ends up executing just `drush`). There doesn't seem to be a way to quote the entire command that doesn't confuse the system...

So, what about moving `_drush_get_os()`, `drush_is_windows()`, and maybe some similar commands into startup.inc? I know @greg-1-anderson voiced some concerns to that #1673 and this is starting to feel hacky.

**Comment by weitzman** [comment]
how about we give up on this issue for the moment and ask folks to run drush.bat instead of the finder. i agree with keeping the finder simple.

**Comment by greg-1-anderson** [comment]
Yes, we wouldn't want to see a lot of functions moving to startup.inc; we should definitely avoid testing for the platform here, and fall back on drush.bat if it is not possible to support Windows in a platform-independent way. 

Would it help Windows out if we renamed `drush.launcher` to `drush.sh`?  That name would be a little confusing for non-Windows users, as some folks might assume that `drush.sh` is what they should symlink to when setting up their $PATH, etc.; we could try to combat this with documentation if making that change helped Windows.

**Comment by mikeker** [comment]
Changing `drush.launcher` to `drush.sh` works better on Windows (`.sh` is associated with the MinGW shell). But it opens Drush in a separate window and you lose the output. I'll poke around some more to see if there's a way around this.

**Comment by mikeker** [comment]
> ask folks to run drush.bat instead of the finder

This does work, at least in my minimal testing of it. Adding something like:

```
alias drush=$HOME/Documents/dev/drush/drush.bat
```

to your `.bashrc` allows Drush to function on Windows, but I assume that prevents you from having separate one Drush per Drupal.

What about this change (971ef3a) instead?

**Comment by kenorb** [comment]
Related: #1696

**Comment by mikeker** [comment]
> So does one need Git bash in order to have sh?

I believe Cygwin has `sh` as well. I know it has `bash`. Cygwin users could use either shell option, though we probably need to update the docs around that.

**Comment by ivanjaros** [comment]
Is this fixed in latest drush release(rc3)?

**Comment by greg-1-anderson** [comment]
No.  Also, it seems that there hasn't been any testing of the drush.phar on Windows. It would be helpful if someone could investigate that, and see how it currently fares.

**Comment by weitzman** [comment]
I tested as far as assuring help and core-status work. Obviously needs more
testing than that.

**Comment by weitzman** [comment]
This seems OK to me. Still want it, @mikeker? Sorry for the delay.

When merging this, we need to squash to hide all the various unneeded commits along the way.

**Comment by tstoeckler** [comment]
The PR doesn't actually fix things properly for me. Looking around the related code we already have a check for whether drush.launcher is executable. On my system drush.launcher is correctly reported as not-executable (as the Shebang is not respected), so that check would suffice. But we currently only perform that check in some cases, not in all. So for me this issue can be fixed, by just moving this check so that it is always performed. It _seems_ that is also generally sensible. I did not want to step on anyone's toes, so didn't create a PR, but you can look at it here: https://github.com/tstoeckler/drush/commit/a3682cb188e74052419c7dbc9b4d5a7d1ac0a646?diff=unified&w=1

**Comment by e-r-n-i-e** [comment]
What about using `drupal-laucher` instead of `drupal.launcher` to avoid the problems on Windows?

**Comment by greg-1-anderson** [comment]
Sounds reasonable to me. Has anyone tried it and confirmed that it works?

**Comment by weitzman** [comment]
Makes sense.

However, Real Bash is now available on Windows. See #1612. Help there is much appreciated.

**Comment by weitzman** [comment]
I debugged this a bit for a co-worker. We had success when we added an association for .launcher extension with `bash.exe` in Control Panel => Default Programs => Associate a file type or protocol with a program. `bash.exe` was found in our case inside of the [Cmder](http://cmder.net/) application. Alternatively it is installed by Acquia Dev Desktop and other programs. Install one of those if you don't have any bash.exe. One command you could use to find out if you have bash.exe is `where bash.exe.

Please report back if this helps.

**Comment by weitzman** [comment]
In related news, Composer suggests that we should not have a drush.bat in our repo and instead [let it create .bat and proxy files](https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-). I'm not sure Composer really passes along arguments and options properly but we could explore this.

**Comment by weitzman** [comment]
Actually some code changes were needed. Those have now landed in master and 8.xz. See #2312

**Comment by v-tsymbalistyi** [comment]
So is there some kind of solution for Windows prompting for a program to open drush.launcher?

**Pull request closed without merging**
