### PR TITLE
Try testing PHP 7.2 on the isolation tests.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Replaces #3333

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
PHP 7.1 is pretty similar to 7.0, so I did not add it here.

**Comment by greg-1-anderson** [comment]
Maybe we should also skip composer-highest on php 5.6?

I kind of hate all of the `excludes`, but I don't think that naming all of the permutations to run is much of an improvement either.

**Comment by greg-1-anderson** [comment]
Or, we could run all of the functional tests on one version of php only, and pick a third testing service (codeship?) to run them on. 😝

**Comment by greg-1-anderson** [comment]
I didn't look for warnings in the test output, but the tests are all green, at least.

Codeship only provides 100 builds per month on the free plan. I looked at Shippable briefly, but couldn't figure out how to start a build on an org (drush-ops). It's authorized for drush-ops, but it doesn't show up in subscriptions.

Maybe what we have is okay.

**Comment by weitzman** [comment]
PR looks good to me.

**Pull request merged**
