### PR TITLE
Environment variables are prepended to Drush command in the wrong order

### PR DESCRIPTION
**Pull request by itafroma**
`drush_build_drush_build_command()` adds environment variables in the wrong place within the command string. For example, if I have an alias like:

```php
$aliases['example'] = [
  '#env-vars' => [
    'FOO' => 'bar',
  ],
];
```

And Drush is loaded via Composer so that its path is something like:

```sh
~/.composer/vendor/drush-ops/drush/drush.php
```

`drush_build_drush_build_command()` will construct a command string that looks like:

```sh
/usr/local/bin/php  -c /etc/php/php.ini env FOO=bar --php=/usr/local/bin/php --php-options=' -c /etc/php/php.ini'
```

This will lead to Drush failing to execute any commands for that alias with the error:

> Could not open input file: env

Because the command trying to load a file named `env` into PHP.

The correct command string should be instead:

```sh
env FOO=bar /usr/local/bin/php  -c /etc/php/php.ini--php=/usr/local/bin/php --php-options=' -c /etc/php/php.ini'
```

Original issue: https://github.com/drush-ops/drush/issues/3078
h/t @axel-rutz for the solution, posted here: https://github.com/axel-rutz/drush/commit/c41235578ab3f9ff6b0dacae3d45a48b3dfae08e

### CODE REVIEW

**Comment by axel-rutz** [comment]
Cool it works for you!

**Comment by greg-1-anderson** [comment]
This used to work in the past. It would be super useful to have a simple test so that it does not break again in the future.

**Comment by weitzman** [comment]
Looks like the test failed. Any ideas?

**Comment by weitzman** [comment]
This feature is failing because it is not implemented in Drush9. Help wanted. https://github.com/drush-ops/drush/blob/88ea047f1aae9039e91336489a4a449b378f9808/examples/example.site.yml#L184

**Comment by weitzman** [comment]
I merged the backport of this PR. Closing this as the feature does not yet exist in 9

**Comment by itafroma** [comment]
Sorry about the failing test: was having trouble getting testing working locally and wanted to try a stab at a quick fix. Thanks for the backport merge!

**Pull request closed without merging**
