### PR TITLE
webmozart/path-util is abandoned

### PR DESCRIPTION
**Pull request by Pasqualle**
#4935

### CODE REVIEW

**Comment by weitzman** [comment]
I think we should use symfony/filesystem since we dont want to maintain our own PathUtil. See #4935

**Comment by Pasqualle** [comment]
But that can't be used with Symfony 4, which means can't be used with Drupal 9, right?
Will there be a new drush for D10 only, or drush will use the abandoned webmozart/path-util until support for D9 is dropped?

**Comment by weitzman** [comment]
Ah right. At the moment, we are not planning a D10 only Drush release. It will probably happen during D10's lifetime, but not for 10.0. So, I'd say that this PR is not much better than the current situation. Just because a package gets abandoned does not mean all its downstreams have to now maintain it. Maybe we can coax @danepowell to maintain a fork of path-util 👅

**Comment by Pasqualle** [comment]
Fixed in https://github.com/drush-ops/drush/pull/5264

**Pull request closed without merging**
