### PR TITLE
Create PR template PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #6038: Add PR template, with Fixes ISSUE link
**Proposal**

You can connect an issue and its PR in Github by including `Fixes #<ISSUE>` in the issue summary, [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

DDEV has a [PR template](https://github.com/ddev/ddev/blob/master/.github/PULL_REQUEST_TEMPLATE.md) which includes the related issue at the top. Eventually the format will be `- Fixes <#ISSUE>` so that the issue and PR are connected, like for example #6004 and #6037.

**Describe the solution you'd like**

Add a PR template for Drush, to make sure that issue and PR are connected, so instead of this in the right hand side of PRs:

> ## Development
> Successfully merging this pull request may close these issues.

... it will say:

> ## Development
> Successfully merging this pull request may close these issues.
> - #6037

**Remaining task**

Create a PR template file, and integrate it.

### PR DESCRIPTION
**Pull request by gitressa**
## The Issue

- Fixes #6038

## How This PR Solves The Issue

Adds a PR template file.

### CODE REVIEW

**Comment by weitzman** [comment]
This doesnt add much useful over a plan description box. We dont want to encourage the filing of useless issues that bifurcate the conversation.

**Comment by gitressa** [comment]
I agree that it should not be required to create a corresponding issue for a PR, PR's should be allowed to stand alone. Drush users linking PR's with issues is a common thing though, if you look under the PR's.

I updated the patch in my branch, to clarify that corresponding a issue to a PR is not required, but it's not getting transferred to this PR, so here it is:

---
name: Pull request
about: For support requests, please use Drupal Answers instead. See https://drupal.stackexchange.com/questions/tagged/drush
---

**Optional: Link pull request and issue, if an issue exists**
Drush pull requests don't require an issue, but if an issue exists, you can connect this PR and the issue:

- Fixes #<issue number>

**Describe the pull request**
A clear and concise description of what the pull request does, for example which problem it solves, or feature it adds.

**Additional information**
Add any other context about the pull request here.

**Comment by gitressa** [comment]
Here are a few PR's, where Drush contributors linked a PR with an issue:

- #5852
- #5861
- #5883
- #5891
- #5895
- #5951
- #5988
- #6019

**Comment by weitzman** [comment]
If there is an issue, of course it makes sense to link it. I dont think we need to tell people about that authoring features like issue linking, just like we dont tell people about markdown and mentioning people.

**Comment by gitressa** [comment]
All right.

**Pull request closed without merging**
