### PR TITLE
Unwanted core upgrade when using make-update

### PR DESCRIPTION
**Pull request by matthijs-va**
When using make-update on a 7.x make file the Drupal core and contrib modules are automatically upgraded to their latest 8.x version. See issue #1842.

Please note that I didn't test if these changes affected any other update-related functionality.

### CODE REVIEW

**Comment by basvdheijden** [comment]
It would be really nice if this got merged.

**Comment by jhedstrom** [comment]
@matthijs-va any chance you could resolve the conflicts and push this up again?

**Comment by jhedstrom** [comment]
I think this was accidentally at 'needs work'. Changes look good, and tests are passing. I'll merge tomorrow in case I missed something with the 'needs work' tag.

**Comment by jhedstrom** [comment]
Thanks all!

**Comment by jhedstrom** [comment]
Fix has been backported to `8.x` as well.

**Pull request merged**
