### PR TITLE
Remove drupal.js from D8 root check.

### PR DESCRIPTION
**Pull request by stefanruijsenaars**

### CODE REVIEW

**Comment by ruijse** [comment]
See https://github.com/drush-ops/drush/issues/1105

**Comment by greg-1-anderson** [comment]
The problem here is that we've weakened the Drush boostrap, making false positives more likely.  Without drupal.js, none of the files we check contain the name "drupal" any longer.

I see two good ways to move forward (lacking an official way to detect the root, as mentioned in #1105):
1. Temporarily remove drupal.js from the bootstrap test.  Put it back in later, once file locations are stable.  Add a comment with the new location, and a TODO to put the check back in later.
2. Check for both the new and the old location of drupal.js.  Put in a comment to remove the old location once we are ready to de-support old Drupal 8 betas (maybe after Drupal 8 stable release).

I'd slightly prefer #2.

**Comment by stefanruijsenaars** [comment]
#2 seem good to me. The new location is core/assets/js/drupal.js

**Comment by stefanruijsenaars** [comment]
Updated the pull request to check for both locations.

**Comment by greg-1-anderson** [comment]
Looks good.  Thanks.

**Comment by stefanruijsenaars** [comment]
Thanks. Can we do a new Drush release so this can be installed on
qa.drupal.org?

2015-02-09 15:56 GMT+01:00 Greg Anderson <notifications@github.com>:

**Comment by greg-1-anderson** [comment]
Seems reasonable.  Discussion on releases is in #1123.

**Pull request merged**
