### PR TITLE
Adding command to process a single queue item.

### LINKED ISSUE #3872: Add command to process a single item from a queue
**Describe the solution you'd like**
As a Drush user I would like to have a command where I can process a single item from a queue.

**Additional context**
I'm working on a script that iterates through all sites on a very large (80+) multisite codebase and clears as many items from a given queue shared across these sites as it can in a given time limit by processing one item of each site's queue per iteration.

**Example:**  
`drush custom-multisite-iterator-command --total-time-limit=60 queue-run-single my_queue`

- custom-multisite-iterator-command: A custom command that iterates through a given site list and executes a given command across these sites as many times as possible in the given time limit.
- queue-run-single: Processes a single item of a given queue.

### PR DESCRIPTION
**Pull request by jose-oliveira**
Fixes #3872 and #4120 .

### CODE REVIEW

**Comment by weitzman** [comment]
Hi. I'm not inclined to add this as a command to Drush core. Perhaps as a --items limit in queue:run.

**Comment by jose-oliveira** [comment]
@weitzman That makes sense. I'll update the PR.

**Comment by jose-oliveira** [comment]
@weitzman PR updated. If you think this can be merged I can also work on adding it to version 9.

**Comment by weitzman** [comment]
ping @juampynr, @davereid, @jhedstrom for their +1/-1 since they have contributed to queue commands.

**Comment by weitzman** [comment]
Fixed in #4120

**Pull request closed without merging**
