### PR TITLE
Add back ::mustRun() w/o params

### PR DESCRIPTION
**Pull request by claudiu-cristea**

### CODE REVIEW

**Comment by weitzman** [comment]
Can you describe a bit whats going on here?

**Comment by claudiu-cristea** [comment]
Sorry, I'm only experimenting. After updating from 9.5.2 to 9.6.0-rc4, I'm getting an error with `sql:cli` in out CI
sqlcli

**Comment by claudiu-cristea** [comment]
@weitzman do you think it could be related?

**Comment by claudiu-cristea** [comment]
Closing this. Opened #3983

**Pull request closed without merging**
