### PR TITLE
Require php 5.5.9 or later.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Because modern.  And supported.  And https://groups.drupal.org/node/473473

Master branch only.

### CODE REVIEW

**Comment by weitzman** [comment]
There are a couple more places. See https://github.com/drush-ops/drush/pull/1424/files. 

I'm not sure those reasons are compelling. We could be making Drush8 unusable by a lot of Drupal 6 and 7 sites with this change.

**Comment by davereid** [comment]
On the other hand, those people won't be able to use Drush 8 with Drupal 8 at all?

**Comment by greg-1-anderson** [comment]
Dreamhost supports php 5.3, 5.4, 5.5 and 5.6.  Hostgator supports php 5.3 through 5.5.  Seems that non-obsolete versions of php are at least available on low-end hosts.

Does Drupal 6 break under php 5.5?  In a few months, php 5.4 will be EOL (http://php.net/supported-versions.php).  In light of that, it seems reasonable to me to have folks on older versions of php use Drush 7, especially considering that you can use the site-local Drush feature to mix-and-match your Drush versions to your site.

**Comment by greg-1-anderson** [comment]
5.5. enters "security fixes only" tomorrow, for one more year.  I guess we could keep this issue open until September, and commit it once 5.4 is actually EOL.

On the flip side, we still have 80% of all users on php 5.4 or later. 

http://w3techs.com/technologies/details/pl-php/5/all

Kinda depressing.

**Comment by greg-1-anderson** [comment]
Of course, 80% is on the server.  There's no reason why devs can't upgrade their work machines to a supported php, and run Drush 7 on the server.

**Comment by weitzman** [comment]
Not going to bump this now since we still target D6 and D7, and those folks are stubbornly not updating. Thinking that we do this for drush9.

**Pull request closed without merging**
