### PR TITLE
Prevent 'drush @local uli' and related commands from executing twice.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Alternate implementation of #3426

### CODE REVIEW

**Comment by nickveenhof** [comment]
That was insanely fast for such an old bug. Thanks @greg-1-anderson. Any timeline when a new drush  8.x release would be made that incorporates this fix?

**Comment by greg-1-anderson** [comment]
We'll need some feedback (or at a minimum, lack thereof!) on the 8.x-dev branch first.

**Comment by Spurlos** [comment]
Unfortunately these changes have broken ssh access using drush and aliases on some specific environments.

> drush @alias ssh
> A site alias is required. The way you call ssh command has changed to 'drush @alias ssh\'. [error]
> command terminated with exit code 1

I was able to ssh successfully to server from local development Ubuntu 18.04 machine, but the same command fails in Docker container that we use. The  base for the container is Alpine linux, which is missing pcntl php extension, which I think is the cause (untested, because alpine repos have no pcntl in them), but that is the only significant difference between local and container php cli extensions diff.

Reverting this commit fixes the issue. And looks like i'm not the only one affected: https://github.com/amazeeio/lagoon/issues/542

**Comment by greg-1-anderson** [comment]
You'll need to do some additional diagnosis to determine which term is causing problems.

Does `drush @alias ssh` work for you in Drush 9?  The bootstrap is quite different on the master branch.

**Comment by lmakarov** [comment]
@greg-1-anderson I submitted a bug report with more context ^

**Pull request merged**
