### PR TITLE
Fix TTY detection for runserver command.

### PR DESCRIPTION
**Pull request by danepowell**
In #4015 we attempted to fix the problem of setting TTY in environments that don't support it, which would throw an exception.

The problem is that the method by which Symfony detects whether an environment supports TTY is more complex than just checking whether /dev/tty is writable, so this could still fail in some environments (e.g. Acquia Pipelines.)

This PR updates the detection to use the exact same check as Symfony, so it's guaranteed to avoid this error.

Note that Symfony Process implemented an "isTtySupported" static method to encapsulate this check in v4, which we could convert to once Drush upgrades to Symfony Process 4.x:
https://github.com/symfony/process/commit/7bc3a902d88f2a65091773b36b640b264285c29f

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Thanks for finding this check in Symfony.  I think what would be best would be:

1. Move this check to a utility class in consolidation/process.
2. Have the check call through to the Symfony static method if it is available.
3. Use this check anywhere Drush tries to use the posix methods.

**Comment by Lettucez** [comment]
This would explain why all of our pipeline builds have been failing.

image

Thank you for your work in getting this addressed.

**Comment by danepowell** [comment]
Okay I added a util class to site-process: https://github.com/consolidation/site-process/pull/41

I updated this PR to depend on that. So you'll need to review/merge that PR first, release a new version of consolidation/site-process, then we'll need to bump the site-process version number in Drush's composer.json.

> Use this check anywhere Drush tries to use the posix methods.

Do you mean that you want me to change every call of `setTty()` in Drush to be `setTty(Tty:isTtySupported())`?

It's a little weird to me that we have to manually check whether TTY is supported for every process, and then manually set it, when Symfony clearly knows if TTY is supported or not and could just enable it automatically somehow. But maybe I'm overthinking this.

**Comment by danepowell** [comment]
I updated the site-process dependency to 2.0.2, so that just leaves the issue of fixing all of the other Posix / TTY calls in Drush.

**Comment by danepowell** [comment]
> Do you mean that you want me to change every call of setTty() in Drush to be setTty(Tty:isTtySupported())?

@greg-1-anderson can you respond to my question above, so we can get this finished? Thanks!

**Comment by greg-1-anderson** [comment]
I don't know the answer to that question. If you go ahead and do that anyway, and the answer is "no", then I'd spot it in the diff. 😄 The answer is "probably yes".

**Comment by greg-1-anderson** [comment]
Maybe `TerminalUtils::isTty` is no longer needed and can be removed?

**Comment by danepowell** [comment]
I already removed the whole `TerminalUtils` class.

**Comment by greg-1-anderson** [comment]
I think I was looking at just one commit instead of the whole patch.

LGTM

**Comment by RoSk0** [comment]
Huge thanks to @danepowell and @greg-1-anderson for fixing this!

Maybe it's time for a new release? We have some good stuff committed since last one https://github.com/drush-ops/drush/compare/9.6.2...master

Ping @weitzman

**Pull request merged**
