### PR TITLE
Make a local $container variable available in drush cli

### PR DESCRIPTION
**Pull request by damiankloip**
It would be cool to have a local `$container` variable available in the REPL.

### CODE REVIEW

**Comment by weitzman** [comment]
Seems reasonable, though I dunno how common it will be to mess with container. I don't want to open the floodgates for lots of local variables. 

I'll leave this open for a few days, and then commit if there are no objections.

**Comment by damiankloip** [comment]
Fair, I think this is pretty common to be honest. If not one of the most common things when using `drush php`, you need the container to do almost anything useful. E.g load entities, entity type data, namespaces, load config, check cache items, path/route related stuff, the list goes on :)

**Comment by dawehner** [comment]
> Seems reasonable, though I dunno how common it will be to mess with container. I don't want to open the floodgates for lots of local variables.

Yeah it would be a huge win DX wise!

Go damian!

**Comment by weitzman** [comment]
OK, lets do it.

* This needs to run only for D8 sites
* Ideally we document this local variable and core-cli in general by adding a new topic. If someone can post text here, I can massage it into a topic. Just give some examples of what you can do with this command.

**Comment by weitzman** [comment]
Ping @damiankloip or @dawehner, for finishing this off if desired.

**Comment by damiankloip** [comment]
@weitzman Sorry about the delay, Just pushed a new commit to add this for D8 only.

As far as examples go, there are some above, and in the issue I opened to use Symfony VarDumper (https://github.com/drush-ops/drush/pull/1102). What else do you think would be good? We could change these examples to use the $container variable?

**Comment by dawehner** [comment]
Nice!

**Comment by dawehner** [comment]
Ready to be committed!

**Comment by damiankloip** [comment]
Thanks @weitzman

**Pull request merged**
