### PR TITLE
Validate module uninstall eligibility

### LINKED ISSUE #2493: Catch ModuleUninstallValidatorException
`drush pmu` doesn't display the reasons from this exception very well and it's sometimes very difficult to parse.

It should catch `\Drupal\Core\Extension\ModuleUninstallValidatorException` and then parse the reasons (splitting by `;`) into a readable list.

### PR DESCRIPTION
**Pull request by markcarver**
Fixes #2493 

**Before:**
screen shot 2016-12-10 at 5 16 49 pm

**After:**
screen shot 2016-12-10 at 5 08 13 pm

X-ref: https://www.drupal.org/node/2834394

### CODE REVIEW

**Comment by weitzman** [comment]
Drush has validate hooks for this purpose.

**Comment by markcarver** [comment]
I know and I thought about adding a validation for this in the drush command, but the reality is that any code that invokes `drush_module_uninstall()` will fatal if it's not validated first (because it doesn't catch the exception from drupal). Thus, this validation is specific to Drupal, not Drush, and should live with that code... IMO.

**Comment by markcarver** [comment]
Ok then... I'm interpreting your silence as a firm "no" and went ahead and created the validation for `pm_uninstall` as you so elaborately dictated.

Note: because of Drush's BC nightmare, I had to add even more cruft to keep the < 8.x implementations of this command working.

I really think this is backwards, but meh, whatever. Just needs to be fixed.

**Comment by weitzman** [comment]
ping @jonhattan for review (pm maintainer)

**Comment by weitzman** [comment]
Moved to #2494 for Drush 9.

**Pull request closed without merging**
