### PR TITLE
Fixes #2671: Perform cache rebuild during updb in same process

### LINKED ISSUE #2671: files.drush.org still has version 8.1.9 as stable
Version 8.1.10 was released nearly 3 weeks ago, but files.drush.org is still serving version 8.1.9 as stable.

An update would be much appreciated! Thanks!

### PR DESCRIPTION
**Pull request by tstoeckler**

### CODE REVIEW

**Comment by hchonov** [comment]
+1 
I really like the solution. We also need backport for the 8.x branch and a new release because of it. We at least need it, because we could not update our D8 sites ATM.

**Comment by weitzman** [comment]
Thanks a lot @hchonov and @tstoeckler. Feel free to open a new PR for backport.

**Comment by tstoeckler** [comment]
Thanks, awesome! Opened https://github.com/drush-ops/drush/pull/2621 for the backport

**Comment by hchonov** [comment]
Thank you for accepting the change, @weitzman!

**Pull request merged**
