### PR TITLE
MySQL 8 support for drush8

### LINKED ISSUE #3830: MySQL 8 support for Drush 8
**Describe the bug**
MySQL 8 was released a few months back, Drush quits with fatal errors when tried to run with MySQL due to various reasons. 

I suggest that we follow the D8 and D7 issued and upgrade `dbtng` component accordingly. 

 - https://www.drupal.org/project/drupal/issues/2986452
 - https://www.drupal.org/project/drupal/issues/2978575

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.x
| Drupal version? | 7.61
| PHP version     | 7.3
| MySQL version     | 8.0
| OS?             | Ubuntu 18.10

**Additional information**

### PR DESCRIPTION
**Pull request by mustanggb**
Fixes #3830 for Drush 8.

### CODE REVIEW

**Comment by weitzman** [comment]
LGTM. Leaving for @greg-1-anderson to merge into 8.x

**Comment by joejoseph00** [comment]
to me it looks like the travic ci succeeded all tests, except one which looks like a glitch because there's another test with the same php version that succeeded.

@greg-1-anderson  lots of developers are working on the mysql 8 compatibility for the next release of Drupal (7.70) and we need this PR because Drupal.orgs test runner for the 7.x branch and mysql 8 build requires drush 8.x 

so in order for the test runner to successfully run our mysql 8 patches for automated testing, we need drush 8.x to be able to work with mysql 8.

see upstream issue in drupal.org https://www.drupal.org/project/drupal/issues/2978575 and also the github drush issue here: #3830

**Comment by greg-1-anderson** [comment]
PR is fine; failing tests are unrelated rot caused by using actual external projects as test fixtures. I'll have to fix those up later.

**Comment by mustanggb** [comment]
Thanks a lot.

**Pull request merged**
