### PR TITLE
Phar side

### PR DESCRIPTION
**Pull request by weitzman**
Task list

- [ ] [Remove realpath() call](https://github.com/drush-ops/drush/blob/8.0.0-rc1/includes/preflight.inc#L484) in drush_preflight_command_dispatch() as it won't work inside a phar. assigned: @greg-1-anderson 
- [ ] Update docs for non-availability of drush.launcher niceties. assigned: @weitzman

### CODE REVIEW

**Comment by weitzman** [comment]
I added a task list in the first post here. One task is assigned to @greg-1-anderson and one to me.

**Comment by greg-1-anderson** [comment]
Perhaps we should remove the shebang from the top of drush.php.  Drush always calls this via `php drush.php`; it has been quite a while since we have sanctioned aliasing `drush` to `drush.php`.

**Comment by greg-1-anderson** [comment]
Awesome!  How are we going to distribute the Drush phar?

**Comment by unn** [comment]
:+1:

**Comment by weitzman** [comment]
For now, folks can build it with `box build`. You can get box tool at https://github.com/box-project/box2. The blockers to attaching a .phar to each release here on Github (thats how we distribute it) are listed at top of this issue.

**Comment by unn** [comment]
Maybe something along the lines of https://github.com/kherge-abandoned/php-phar-update as well?

**Comment by weitzman** [comment]
That one is abandoned, but perhaps https://github.com/padraic/phar-updater is maintained and as useful.

**Comment by sint** [comment]
While being happy to have found about your Drush phar efforts i am kinda puzzled that you've rejected me when i was requesting an alternative to a composer only setup. Isn't this exactly it? Will there be a Drush 7 phar, too?

**Comment by weitzman** [comment]
Read a bunch and found a [Symfony Console command by the maintainer that actually uses the phar-updater library](https://github.com/padraic/humbug/blob/master/src/Command/SelfUpdate.php)

**Comment by weitzman** [comment]
If folks want to play with it, attached is drush.phar as of right now. Remove the .txt filename suffix that Github requires for comment attachments. Place drush.phar in your $PATH, and feel free to remove the .phar suffix for just `drush`. 

I'd love to hear feedback on how it works for you - [drush.phar.txt](https://github.com/drush-ops/drush/files/23080/drush.phar.txt)

**Comment by sint** [comment]
Tried it and it works perfectly. Just download, rename and go. Thanks allot

**Comment by weitzman** [comment]
FYI, drush.phar is now [the default install method](docs.drush.org/en/master/install/) and is [auto-uploaded to each Drush release](https://github.com/drush-ops/drush/blob/master/.travis.yml#L68).

The drush.phar self updater is still outstanding. We should open a new issue for that.

**Comment by weitzman** [comment]
self updater is now #1980

**Pull request closed without merging**
