### PR TITLE
Fix incorrect script name when Drupal uses a domain + subdir

### PR DESCRIPTION
**Pull request by Chi-teck**
This only happens when Drupal is installed in subdirectory and site URL is passed by means global uri option like follows.
`drush <CMD> --uri=http://localhost/subdirectory`

Because of wrong script name some Drupal global variables (_$base_path_ and _$base_url_) get wrong values.

### CODE REVIEW

**Comment by Chi-teck** [comment]
The URLs generated by Drupal core Url class are still wrong though.

**Comment by Chi-teck** [comment]
The simplest way to reproduce the issue is to put the following code to some command and call it with `uri=http://llocalhost/path/to/drupal/` option.
```
$this->io()->write((new Url('system.admin'))->toString());
```
Instead `/path/to/drupal/admin` it prints `/admin`.

**Comment by weitzman** [comment]
tests are failing, unfortunately.

**Comment by weitzman** [comment]
Still needed?

**Comment by Chi-teck** [comment]
The bug still exists in `master`. I am having troubles with setting up SUT. This might be related to my local environment (PHP 7.2).

**Comment by greg-1-anderson** [comment]
You must use Drupal 8.4.4 (release yesterday) if you are using PHP 7.2. Earlier versions did not support 7.2.

**Comment by Chi-teck** [comment]
I am using the latest code form 8.5.x Git branch. Is Drush itself compatible with PHP 7.1 and PHP 7.2? It appears it is not tested against these PHP versions. 
https://github.com/drush-ops/drush/blob/master/.travis.yml#L11

**Comment by hansfn** [comment]
Since this issue most likely is the cause for the missing subdir when using `drush uli`with uri option, I'm adding it here so other people can find it:

`drush uli --no-browser --uri=http://nonexisting.domain/folder

returns "http://nonexisting.domain/user/reset/1/[...]" without the subdir in the URL.

**Comment by ao2** [comment]
Some other commands to reproduce the issue are in https://github.com/drush-ops/drush/issues/3463

@Chi-teck can you rebase your branch on the latest drush version so that we can validate your changes and go forward with this issue?

Thanks,
   Antonio

**Comment by weitzman** [comment]
Github updated the PR so its up to date with master. Still is failing tests tho.

**Comment by ao2** [comment]
Thanks @weitzman

**Comment by gitressa** [comment]
It works for sub-folders if there is a trailing slash:

```
$ drush uli --uri=http://nonexisting.domain/folder
http://nonexisting.domain/user/reset/1/153...uPBiz5lA/login
```

```
$ drush uli --uri=http://nonexisting.domain/folder/
http://nonexisting.domain/folder/user/reset/1/1539196592/tMD_...If7mKyRvQ/login
```

**Pull request closed without merging**
