### PR TITLE
Search for site-aliases outside the web root

### PR DESCRIPTION
**Pull request by webflo**
Follow-up for https://github.com/drupal-composer/drupal-project/pull/35

### CODE REVIEW

**Comment by weitzman** [comment]
I think this got done in #1480. If not, please post here and I will reopen.

**Comment by webflo** [comment]
I tried it with drush HEAD a few minutes ago, maybe the bug is related to the new drush launcher?

**Comment by weitzman** [comment]
We should really test aliases and commandfile searchpaths like we do config. See \Unish\contextCase. /cc @greg-1-anderson in case he has insight here.

**Comment by weitzman** [comment]
It looks to me like the new ROOT/../drush/site-aliases directory got documented in #1480 but it isn't working. I've asked @greg-1-anderson to look into it.

**Comment by webflo** [comment]
Thanks!

**Comment by greg-1-anderson** [comment]
Added a test and merged.

**Pull request merged**
