### PR TITLE
#3163: don't use STDOUT as a function parameter default, because the …

### PR DESCRIPTION
**Pull request by douggreen**
…define actually calls fopen()

### CODE REVIEW

**Comment by douggreen** [comment]
See https://github.com/drush-ops/drush/pull/3171

**Comment by douggreen** [comment]
Sorry for the extra work. I'd hoped tests would of caught that. We now are back to the code that I'd originally written. The code original merged just looked cleaner, but it was alas, untested.

**Comment by greg-1-anderson** [comment]
I just tested HEAD of `master` without this PR (using STDOUT as a default parameter) and it seems to work.

I'm still +1 on merging this once the tests pass. Maybe works in newer versions of php, but not necessarily older?

**Comment by douggreen** [comment]
```
```
Yea, maybe. My PHP is not cleaning up the file pointer when it's opened as part of the function parameters, but does when it's opened in the function.

The original solution looked cleaner. But I don't like calling a function outside a function. It's dangerous. This is a bit different. It's calling a function in the function argument, but it still seems dangerous.

I get these errors, not on every drush command, but on the site-install.
```
opendir(/Users/douggreen/src/drush/includes/../vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/Template):[warning]
failed to open dir: Too many open files filesystem.inc:685
```

**Comment by douggreen** [comment]
Odd, I'm now getting that same error on the old solution. :(

**Pull request closed without merging**
