### PR TITLE
Add diff feature to make-update

### PR DESCRIPTION
**Pull request by basvdheijden**
The `drush make-update` command turns out to be really useful. However, I miss being able to see a diff between the old makefile and the newly (updated) one. Especially if you have a big makefile, it's not apparent which modules got updated.

By specifying the `--diff` flag, `drush make-update` gives you a diff between the new and old makefile.

### CODE REVIEW

**Comment by jonhattan** [comment]
I'd prefer that --diff (or --show-diff) always show the diff on screen, and that --result-file always save the updated makefile.

**Comment by BasVanDerHeijden** [comment]
Good point. To be sure I know what you mean:
specifying ``--show-diff`` together with ``--result-file=bla.make`` shows the diff to the screen _and_ saves the resulting makefile to bla.make?
And if I only do a ``--show-diff``, it shows to the screen but doesn't save the updated makefile?

**Comment by jonhattan** [comment]
> specifying --show-diff together with --result-file=bla.make shows the diff to the screen and saves the resulting makefile to bla.make?

yes

> And if I only do a --show-diff, it shows to the screen but doesn't save the updated makefile?

Not sure. At present, if result-file is not given, the makefile is printed to the screen. We could print the diff and then the makefile, or the diff only.

**Comment by BasVanDerHeijden** [comment]
I would say the diff only, so you could potentially do something with the output (i.e. pipe to patch command). I will go ahead and implement this

**Comment by jhedstrom** [comment]
Any possibility of adding a test for this? Also needs merge conflicts resolved.

**Comment by weitzman** [comment]
make is deprecated

**Pull request closed without merging**
