### PR TITLE
Skip dependencies on config import/export when modules are skipped (--skip-modules)

### PR DESCRIPTION
**Pull request by gaelg**
See https://github.com/drush-ops/drush/issues/1820

### CODE REVIEW

**Comment by bircher** [comment]
The approach here is very much centred around adding extra functions.
I think it would be possible to take care of the dependency filtering in the `\Drush\Config\CoreExtensionFilter` with a little help from `\Drupal\Core\Config\ConfigManagerInterface::findConfigEntityDependents`

See https://github.com/nuvoleweb/config_split/blob/8.x-1.x/src/Config/SplitFilter.php#L62 (though maybe not the perfect example, then the `CoreExtensionFilter` just needs to ignore the blacklisted configuration.

**Comment by gaelg** [comment]
I rewrote this from scratch using bircher's advice. The code should be much better now, as it reuses existing code when possible (dependency detection, modules sorting).
I'd love to have feedback on this so that I can work on it during the DrupalCon Dublin sprint tomorrow, for it to be hopefully committed.

**Comment by weitzman** [comment]
@greg-1-anderson would be the person to review this. I will say that I have been resistant to this feature existing in Drush core. I'd rather not see it grow in complexity within core. Having said that, I defer to Greg's judgement on this PR.

**Comment by gaelg** [comment]
Allright, thank you for the quick feedback! It would have been better if this issue had been closed sooner if it's a "won't fix", but anyway I learnt much by trying to contribute to this.
IMHO the feature is "skip-modules" (already in drush core) and this PR is more a bugfix of the feature.
If someone tries to just use skip-modules right now, its config will never import. It needs a good .gitignore file referencing any dependency. If it's only for Devel, it's easy, but when you're used to have many dev modules enabled, it can be harder.
For various reasons, it might indeed be relevant to have this out of core. But then maybe the whole skip-modules feature should be out, no? At least if would mean some changes to core to make it extensible.

**Comment by robertoneshoe** [comment]
@gaelg, I've tested your pull request, but there's still some unwanted config being exported. For example, when Devel is enabled, system.menu.devel is still being exported.

**Comment by gaelg** [comment]
@robert-os Yes, it's known problem from the Devel module that did not correctly declare the dependency. But it's solved in the latest dev version of Devel.

**Comment by weitzman** [comment]
This looks like a useful improvement. Would be great if someone found time to review it.

**Comment by bircher** [comment]
I looked over it, and I like the direction this is going in.
It is a good idea to make the source storage available to more than just one filter operation. I found out that it is also useful to have the wrapped storage available. So instead of passing it as an argument to all filter options why not give it to the filter at the start.

You could make your life a lot easier if you would base this PR on top of #2313. My estimate would be around 25 lines of code changes to filter dependent configuration.

In addition it would be good to have some automated tests.

**Comment by weitzman** [comment]
Please work with config_split project. --skip-modules is moving out of Drush and into there.

**Pull request closed without merging**
