### PR TITLE
Remove DRUSH_EXECUTION_COMPLETED and DRUSH_EXIT_CODE handling

### LINKED ISSUE #3749: drush pm:security -n wrong status-code
**Describe the bug**
drush returns a statuscode indicating that there is an error, although there is none.
This **wil** terminate good scripts tasked with updating a drupal-site in the moment when they need to run flawlessly.

**To Reproduce**
Install a Drupal-Site expecting a core-update e.g. 8.6.1.
Run `drush pm:security -n ; echo $?` .

**Expected behavior**
I expect to see a non-zero status-code only when there is an error causing drush not to perform the task requested, because of varying conditions.
Running `drush pm:security -n` should not return non-zero when there is an update as getting an update is expected behaviour and not an error.

**Actual behavior**
A script written to stop when an error occures as to not do any damage will not be able to perform an update.
e.g.

`
function handleErrors() {
$statusCode=$?;
......
exit $statusCode;
}
trap handleErrors ERR

.....
......drush pm:security -n --pipe......
..... update-action never executed.........
`

**Workaround**
Disable Trap with `trap - ERR`.
This has the drawback that you will not be able to respond to an actual error happening.

### System Configuration
Linux
Drupal 8.6.1
Drush Commandline Tool 9.2.3
PHP 71

**Additional information**
None.

### PR DESCRIPTION
**Pull request by weitzman**
I think its OK to remove these during a minor release since they are long ancient and non-recommended APIs. Happy to discuss.

One notable change is that pm:security now exits with 0 when there an update is found. This fixes #3749. I had to do this since I can no longer set a 1 exit code AND print my structured output, even when the command returns a ResultData object.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Are we just giving up on the "Drush command terminated abnormally due to an unrecoverable error"  feature? While that caused a lot of confusion, not having any indication that the website called `exit()` might be even worse.

I'm not sure about changing the exit-status behavior of pm:security in a minor release, though. This could interfere with folks' security-update checking scripts. It might be better to enhance annotated command / output formatters to allow for returning structured data with an exit code.

**Comment by greg-1-anderson** [comment]
Here's a PR in annotated command that would allow both an exit code and result data to be returned by the same annotated command:

https://github.com/consolidation/annotated-command/pull/167

If this works well for our purpose, then I could make a stable release with this addition.

**Comment by weitzman** [comment]
That looks great. Thanks Greg.

**Comment by greg-1-anderson** [comment]
I'm okay with losing "Drush command terminated abnormally due to an unrecoverable error" if you really want to, but I sort of think we should keep it. We could try without for a while and see how it goes.

**Comment by weitzman** [comment]
I brought it back in recent commits. https://github.com/drush-ops/drush/pull/3780/files#diff-00e1d309f15af5b596b61de17b456130R36

**Pull request merged**
