### PR TITLE
Test with a patched Drupal 8.x.4 (Symphony 3.2)

### PR DESCRIPTION
**Pull request by weitzman**

### CODE REVIEW

**Comment by ms-slasher13** [comment]
Didn't test it yet, but it should be 
`"drupal/core": "symfony32",`
and not 
`"drupal/core": "dev-symfony32",`

**Comment by weitzman** [comment]
I get an invalid constraint error from composer when specified that way.

**Comment by catch56** [comment]
I'd like to commit https://www.drupal.org/node/2712647# to 8.4.x fairly soon, but we've been partly waiting to do so until drush is updated. I'm not clear from reading this issue what the status of the 3.2 upgrade is, is it still reverted pending this issue?

**Comment by weitzman** [comment]
@catch56  - yes, thats the status. 

this issue is close. we just need someone to look into why composer-highest.json won't build. the error is in the travis log - https://travis-ci.org/drush-ops/drush/jobs/215225668

**Comment by webflo** [comment]
I think the PR is wrong. Drush requires ``drupal/core`` but the custom repo provides "drupal/drupal".

**Comment by webflo** [comment]
You need a fork of https://github.com/drupal-composer/drupal-core

**Comment by webflo** [comment]
New PR in https://github.com/drush-ops/drush/pull/2692

**Comment by weitzman** [comment]
I got this working in #2624. Lets discuss there.

**Pull request closed without merging**
