### PR TITLE
Prevent drush make failures

### LINKED ISSUE #1887: Drush make fails sometimes due to Backend invoke limitation
### Env:

PHP 5.6.16 (cli) (built: Dec  5 2015 18:05:12)
### Issue

When I try to build a make file with `drush make myfile.make.yml mydest` I receive the error _No projects passed to drush_make_process_ and the build fail, but only when some modules are in the make file.
### Description

I'm try to build the makefile (`test_ko.make.yml`):

```

---
core: 6.x
api: 2

projects:
  drupal:
    version: '6.37'
  advuser:
    version: '3.0-alpha2'
  autoload:
    version: '2.1'
  content_taxonomy:
    version: '1.0-rc2'
  cck:
    version: '2.10'
  date:
    version: '2.10'
  unique_field:
    version: '1.4'
  computed_field:
    version: '1.0'
  filefield:
    version: '3.13'
  force_password_change:
    version: '3.4'
  google_analytics:
    version: '4.1'
  imageapi:
    version: '1.10'
  imagecache:
    version: '2.0-rc1'
  imagefield:
    version: '3.11'
  jquery_update:
    version: '2.0-alpha1'
  libraries:
    version: '1.0'
  link:
    version: '2.11'
  noreqnewpass:
    version: '2.0'
  path_redirect:
    version: '1.0-rc2'
  pathauto:
    version: '1.6'
  poormanscron:
    version: '2.2'
  print:
    version: '1.19'
  smtp:
    version: '1.1'
    do_recursion: 0
  token:
    version: '1.19'
  token_filter:
    version: '1.0'
  translation_helpers:
    version: '1.0'
  userplus:
    version: '2.5'
  uuid:
    version: '1.0-rc2'
  views:
    version: '3.2'
  views_customfield:
    version: '1.0'
  views_nivo_slider:
    version: '2.0'

defaults:
  projects:
    subdir: 'contrib'
```

that fail with the error:

```
Beginning to build test_ko.make.yml.                                                                                                                                                         [ok]
drupal-6.37 downloaded.                                                                                                                                                                      [ok]
No projects passed to drush_make_process                                                                                                                                                    [error]
Drush Make failed to download all projects. See the log above for the specific errors.                                                                                                       [error]
```

after some debug i found that a similar make file (`test_ok.make.yml`, changed `views_nivo_slider`with `devel` module) complete without issue:

```

---
core: 6.x
api: 2

projects:
  drupal:
    version: '6.37'
  advuser:
    version: '3.0-alpha2'
  autoload:
    version: '2.1'
  content_taxonomy:
    version: '1.0-rc2'
  cck:
    version: '2.10'
  date:
    version: '2.10'
  unique_field:
    version: '1.4'
  computed_field:
    version: '1.0'
  filefield:
    version: '3.13'
  force_password_change:
    version: '3.4'
  google_analytics:
    version: '4.1'
  imageapi:
    version: '1.10'
  imagecache:
    version: '2.0-rc1'
  imagefield:
    version: '3.11'
  jquery_update:
    version: '2.0-alpha1'
  libraries:
    version: '1.0'
  link:
    version: '2.11'
  noreqnewpass:
    version: '2.0'
  path_redirect:
    version: '1.0-rc2'
  pathauto:
    version: '1.6'
  poormanscron:
    version: '2.2'
  print:
    version: '1.19'
  smtp:
    version: '1.1'
    do_recursion: 0
  token:
    version: '1.19'
  token_filter:
    version: '1.0'
  translation_helpers:
    version: '1.0'
  userplus:
    version: '2.5'
  uuid:
    version: '1.0-rc2'
  views:
    version: '3.2'
  views_customfield:
    version: '1.0'
  devel:
    version: '1.28'

defaults:
  projects:
    subdir: 'contrib'
```

I already tested with a lot of different modules, so is not a issue related only to `views_nivo_slider` module.

After some more debug i found that the issue seems related to a different behavior on `drush_backend_invoke_concurrent`. It look like a error on invoke `make-project` that miss the `projects-location` parameter.

Anyone have a similar issue?

### PR DESCRIPTION
**Pull request by acrollet**
Resolves #1887

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Could you explain the loop termination conditions, and the desired result?  Looks like you terminate if you have spent more than 0.5 seconds, or you do not get a string, or you get an empty string. This seems to terminate while you are still receiving characters; is that correct?

**Comment by acrollet** [comment]
@greg-1-anderson so this is ironic, but my computer went out for repair and I can no longer reproduce the original issue. Closing this.

**Comment by acrollet** [comment]
@greg-1-anderson well, the problem has cropped up again. Have wracked my mind in vain to try and think of any environment changes I've made that could be related. I've updated the PR to simplify the loop termination conditions.

**Comment by alvar0hurtad0** [comment]
@greg-1-anderson I've reproduced on my local with OSX and MAMP and the PR solves the problem.

**Comment by JTelcontar** [comment]
I was also having the problem in #1887 using Drush 8.1.12, MacOS 10.12.6, and MAMP PRO 4.2.

I tested the changes in this PR against the 8.x branch and successfully ran `drush make` with my YAML makefile. No more "No projects passed to drush_make_process" error.

(Note that I also attempted to test against the master branch, but for this project I cannot do a make-convert and move to Composer. Due to this, I received an Exception and could not continue.)

**Comment by greg-1-anderson** [comment]
It would be good if the return data from [stream_get_metadata](http://php.net/manual/en/function.stream-get-meta-data.php) could be used to read more than one byte at a time.

Also, this now only times out if the threshhold is exceeded by any one read operation. Seems like maybe the start timer should only be reset when data is successfully read, so that the timeout happens if a period of time with no output passes.

Is stream_get_contents blocking or non-blocking here?  I am presuming it's non-blocking.

**Comment by askibinski** [comment]
Can confirm this patch fixes the "No projects passed to drush_make_process" error on OSX/MAMP 4.2 / PHP 7.1.6 / Drush 8.1.15.

**Comment by greg-1-anderson** [comment]
Apparently solved by the PR above, but make is maintenance only; closing.

**Pull request closed without merging**
