### PR TITLE
Fix datestamp to time of last commit.

### PR DESCRIPTION
**Pull request by danepowell**
see issue: #1059

### CODE REVIEW

**Comment by jhedstrom** [comment]
This is great. The changing timestamps drive folks nuts when dealing with version controlled make files.

For some reason, the date printed out in the failing test is [1970](https://travis-ci.org/drush-ops/drush/jobs/51089511#L256)

**Comment by danepowell** [comment]
Looks like I missed a call to drush_pm_inject_info_file_metadata. Fixed that.

Unfortunately, it doesn't actually seem to be grabbing the git commit date... not sure why

**Comment by danepowell** [comment]
Okay that's fixed. May still need to update tests since they are expecting to see today's date in the info file.

**Comment by danepowell** [comment]
This should be good to go. The failing tests seem unrelated to this PR. Let me know if you want me to rebase it to clean it up.

**Comment by jhedstrom** [comment]
Awesome! Thanks!

**Pull request merged**
