### PR TITLE
Allow updating modules with new service dependencies

### PR DESCRIPTION
**Pull request by jcisio**
Add feature from Drupal 8.7.5.
@see https://www.drupal.org/node/2863986

This (partially?) fixes https://github.com/drush-ops/drush/issues/3574

### CODE REVIEW

**Comment by weitzman** [comment]
Perhaps @deviantintegral is up for a review here?

**Comment by pfrenssen** [comment]
I think this approach is mostly harmless but not the "right way". This change will always invoke the `UpdateCompilerPass`, while the idea behind this is that it should only happen when using the `UpdateKernel`. So only when updates are being performed. When not doing updates core uses `DrupalKernel` which does not invoke `UpdateCompilerPass`.

With this change we will _always_ silently drop services from the container if they have missing dependencies, but this is not the desired behavior if we're not updating. It might even cause critical bugs if a typo is being made in a `*.services.yml` file and this is not noticed before pushing to production. Normally when a required dependency is missing (due to a module not being enabled, a file not being committed, or a typo in the yml file) an exception will be thrown when the container is compiled, and this alerts the developer that something is seriously wrong with the dependency chain.

The correct approach would be to use the `UpdateKernel` for all commands that are executed during a site update. This is already the case for all commands in `UpdateDBCommands` - they are tagged with the annotation `@kernel update`. They should already work fine on Drupal 8.7.x.

But I have discovered today that there is (at least) one more command that is used in the site update procedure which is not using the right kernel: `config:import`. It still crashes with this exception. I was not aware of this PR yet, I have proposed an approach in #4217.

**Comment by deviantintegral** [comment]
TIL'ed about `@kernel update` - that's very nice.

**Comment by weitzman** [comment]
#4217 fixed this AFAICT.

**Pull request closed without merging**
