### PR TITLE
Fixes #4812: Support Robo 3 while maintaining compatibility with Robo 2 and Robo 1.

### LINKED ISSUE #4812: Can't update robo
**Describe the bug**
We are currently on drush/drush 10.6.0 per the recommendation of Drupal 9 we are on PHP 8
But drush is requiring consolidation/robo: ^1.4.11 || ^2 which IS NOT compatible with PHP 8
Robo has a version 3 that is but we can't update because Drush is blocking that.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Going to take a swing at #4812. First, though, let's run the tests with latest dependencies and no other changes to see if maybe #4813 is related to the new Annotated Command library release.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
First test failed due to bc break in Annotated Command 4.3.0.  After the release of Annotated Command 4.3.1, I re-ran the tests, and now the same commit passes.

Time to move on to updating to Robo 3.

**Comment by greg-1-anderson** [comment]
OK, we have a small problem.

In league/container 2.x, a container is a `League\Container\ContainerInterface`

In league/container 3.x, a container is a `Psr\Container\ContainerInterface`

This isn't a problem in DependencyInjection.php, as all of the references are on protected methods, so I can just change those. However, in Drush.php we have:
```
public static function setContainer(ContainerInterface $container)
public static function getContainer(): ?ContainerInterface
```
I **could** just drop these two typehints. Usually, changing a method signature is considered a b/c break, but the Drush class is just a collection of static methods, so no one will be overriding it. If I took the typehints off, any existing module / extension code that used the Drush class should continue to work the same way.

There is the other issue that if someone uses `getContainer()` and then tries to extend Drush's container by adding more things to it, that code will break if it runs with a Robo 3 / League 3 site. No one should be extending Drush's container, though.

Close enough to continue on?

**Comment by weitzman** [comment]
That’s fine yes. FYI I did some of this work in #4798. It makes sense to break it out separately here.

**Comment by greg-1-anderson** [comment]
Yay, we are green here already. I'm going to make a couple minor code style changes, then this will be ready for review.

**Comment by greg-1-anderson** [comment]
This turned out to be easier than I thought; `alterServicesForDrush` and `injectApplicationServices` do not need to vary based on league/container version, and the two methods to add in the Drush services are very regular between the 2.x and 3.x version.

**Review by weitzman — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
