### PR TITLE
Add Drush Test Traits

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Note that these must go in `autoload`, not `autoload-dev` so that they will be available to clients that may include Drush as a dependency (e.g. in a Drupal site) for testing.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Working, except for the strange Appveyor failure.

Drush 8 Branch: https://github.com/drush-ops/drush/pull/4008
Example Drush Extension PR: https://github.com/drush-ops/example-drush-extension/pull/1

It would take more work to replace Drush's own `drush()` function with the one in the test traits; not planning on doing that right away, but maybe someday.

**Comment by greg-1-anderson** [comment]
kk I'll docs it up

**Comment by greg-1-anderson** [comment]
@weitzman LMK if you have any feedback on the docs updates

**Comment by weitzman** [comment]
Lgtm.

**Pull request merged**
