### PR TITLE
Fixes #5253: Drush user-cancel command blocks the user account instead of deletion.

### LINKED ISSUE #5253: Drush user-cancel command blocks the user account instead of deletion
**Describe the bug**
Drush user-cancel command blocks an user account instead of deletion. For blocking users there is user-block command.

**To Reproduce**
Run `drush user-cancel username -y`

**Expected behavior**
The account is deleted, content is reassigned to the Anonymous user.

**Actual behavior**
The account is blocked.

**Workaround**
The only way to do it manually from Drupal UI.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.x/1
| Drupal version? | 9.x
| PHP version     | N/A
| OS?             | N/A

### PR DESCRIPTION
**Pull request by xopoc14**
Fixes #5253

### CODE REVIEW

**Comment by weitzman** [comment]
Thanks. This needs a test to check reassignment, and is a backward compat change so would need to go into next major release.

**Comment by xopoc14** [comment]
> Thanks. This needs a test to check reassignment, and is a backward compat change so would need to go into next major release.

Sure, I am busy at the moment, will do it as I have time

**Comment by weitzman** [comment]
Would you mind editing the command description and options/examples so that they are clear on what happens to the user, and what happens to the content.

**Comment by weitzman** [comment]
This got resolved with a new --reassign-content option

**Pull request closed without merging**
