### PR TITLE
Fix SQL hostname for localhost #2017

### PR DESCRIPTION
**Pull request by AdamPS**
It would be great to get this one in please because it solves a potential security problem.  See #2017 for full details.

Also fixes missing error handling which I discovered whilst testing.

### CODE REVIEW

**Comment by weitzman** [comment]
Merged into master branch in 92fa9a4. If we get no complaints for a month, I'm willing to merge into 8.x as well. 

Thanks for sticking with this @AdamPS .

**Comment by AdamPS** [comment]
@weitzman  Great, thanks.  Forgive me, I'm still new to git and I get confused easily.  It looks like you merged the changes in my commit into your own repository, added some comments then checked in.

So even though you didn't specifically pull my PR, I can now delete the branch for my PR without harm - correct?

**Comment by AdamPS** [comment]
@weitzman 2 months have now passed so please can you merge into 8.x as well?

**Comment by weitzman** [comment]
Sorry for the delay. 

Some of this code went in with other issues: sql->drop() and sql->drop_or_create(). If you could provide a PR for 8.x that would be awesome.

**Comment by AdamPS** [comment]
@weitzman I'm afraid I have got a bit lost with the sequence of events that you have taken so far.  I only started using git and git-hub to try and get some fixes into drush so my websites keep working (still hoping - thanks for your time).  I spent half an hour and have tried to do as you ask:
git checkout 8.x
git cherry-pick 92fa9a439fc5ec26cff3fb68a9e7cfd0d4076d2d
Commit to my clone, and PR https://github.com/drush-ops/drush/pull/2288
The PR seems to have been created but there is an error message about conflicts.
"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests."

Hopefully you know what to do at this point, as I'm not sure what I can do.  There were no conflicts when I ran all the merging and commit steps on my clone.

In case of confusion, the only part of the fix the original commit that is really important is these 6 lines in lib/Drush/Sql/Sqlmysql.php.  

// - For a localhost database, create a localhost user.  This is important for security.
//   localhost is special and only allows local Unix socket file connections.
// - If the database is on a remote server, create a wilcard user with %.
//   We can't easily know what IP adderss or hostname would represent our server.
$domain = ($this->db_spec['host'] == 'localhost') ? 'localhost' : '%';
$sql[] = sprintf('GRANT ALL PRIVILEGES ON %s.* TO \'%s\'@\'%s\'', $dbname, $this->db_spec['username'], $domain);

Thanks

**Pull request closed without merging**
