### PR TITLE
Porvide a DRUSH_COMMAND env variable

### PR DESCRIPTION
**Pull request by w3wfr**
Hi,

This PR provide a DRUSH_COMMAND environment variable that is needed to turn around some bad behavior in Windows such as when a PHP extension file open directly in a given program from the command line :'(

This happens for example when using `drush rebuild` and break any automated recursive treatments.

This patch force Drush to use an external drush.bat path (such as C:\drush\drush.bat) instead of the vendor path approach.

Notice: as it is an environment, drush.bat should not just comment such a line in `drush.bat` file, but provide an empty value to make sure the external path is not used if the need differs from different scripts (such as `drush make` that works best with internal vendor drush path).

    :: To DEPLOY with drush rebuild
    ::SET DRUSH_COMMAND=c:\drush\drush.bat

    :: To MAKE with drush make (no space after the equal sign)
    SET DRUSH_COMMAND=

Regards,
Alexandre

### CODE REVIEW

**Comment by w3wfr** [comment]
As a complement, to start a drush command line with this env var without actually affecting the environment, one can use this syntax in TFS / Jenkins scripts:

	cmd /C "set DRUSH_COMMAND=c:\drush\drush.bat && drush @drupalsite.alias rebuild"

**Comment by greg-1-anderson** [comment]
What is the bad value of `$_SERVER['DRUSH_COMMAND']` that necessitates this environment variable?

Would it be possible for the drush.bat script to provide the value necessary to make the Drush redispatches work correctly?  I don't like the requirement that Drush must be called in different ways depending on the task being accomplished.

**Comment by w3wfr** [comment]
Hi Greg,

Towards what I describe I am not sure to understand what you bad value. 

When a drush command iterates to trigger other drush commands directly through php in the command line, windows open the php file with the default program instead of using php... Quite weird!

As it appears to iterates externally through os stack, going through drush or drush.php meet the same limits as when we start any drush command and we need to use drush.bat I steady to make sure default editor program is not used.

**Comment by greg-1-anderson** [comment]
@w3wfr if that is the case, then why is it necessary to insure that DRUSH_COMMAND is empty when calling `drush make`?

**Comment by w3wfr** [comment]
Hi Greg,
Because it doesn't work... :-(

I just made a `drush cc drush` because `drush make` error messages ask for it.

The temp directory error is reproduced on other windows environment where we have made similar testings.

Regards.
Alexandre

    $ cmd /C "set DRUSH_COMMAND=c:\drush\drush.bat && drush cc drush"
    'drush' cache was cleared.

    $ cmd /C "set DRUSH_COMMAND=c:\drush\drush.bat && drush make foo.make foo"
    Beginning to build foo.make.                                                                                                                                [ok]

    The drush command '  --backend=2 --yes --root= --uri=  pm-download drupal-7.38   --destination=c:\\temp/make_tmp_1442863074_560057e2bb8cf' could not     [error]

    be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.
    Illegal string offset 'site' backend.inc:1030                                                                                                          [warning]

    The command could not be executed successfully (returned: The drush command '  --backend=2 --yes --root= --uri=  pm-download drupal-7.38                 [error]

    --destination=c:\\temp/make_tmp_1442863074_560057e2bb8cf' could not     [error]
    be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.
    , code: 1)
    drupal-7.38 downloaded.                                                                                                                                     [ok]

    The drush command '  --backend=2  make-process c:\\temp/make_tmp_1442863074_560057e2bb8cf' could not be found.  Run `drush cache-clear drush` to         [error]

    clear the commandfile cache if you have installed new extensions.
    Illegal string offset 'site' backend.inc:1030                                                                                                          [warning]

    The command could not be executed successfully (returned: The drush command '  --backend=2  make-process c:\\temp/make_tmp_1442863074_560057e2bb8cf'     [error]

    could not be found.  Run `drush cache-clear drush` to         [error]
    clear the commandfile cache if you have installed new extensions.
    , code: 1)
    Source directory c:\temp/make_tmp_1442863074_560057e2bb8cf\__build__ is not readable or does not exist.                                                  [error]

    Cannot move build into place.                                                                                                                            [error]

**Comment by greg-1-anderson** [comment]
The above output shows that your PR is not working correctly.  This will need to be cleaned up, so that Drush redispatches happen consistently before we can proceed here.

**Comment by w3wfr** [comment]
I mean: It doesn't work when `DRUSH_COMMAND` is used with `drush make`. This is what precedent comment was illustrating

    $ drush make foo.make foo
    Beginning to build foo.make.                                                                                                                                [ok]

    drupal-7.38 downloaded.                                                                                                                                     [ok]

    Project admin_menu contains 3 modules: admin_menu_toolbar, admin_devel, admin_menu.
    admin_menu-7.x-3.0-rc5 downloaded.                                                                                                                          [ok]

    Project bean contains 5 modules: bean_uuid, bean_usage, bean_entitycache, bean_admin_ui, bean.
    bean-7.x-1.9 downloaded.                                                                                                                                    [ok]

    Project ctools contains 10 modules: views_content, term_depth, stylizer, page_manager, ctools_plugin_example, ctools_custom_content, ctools_ajax_sample, ctools_
    access_ruleset, bulk_export, ctools.
    ctools-7.x-1.7 downloaded.                                                                                                                                  [ok]

    diff-7.x-3.2 downloaded.                                                                                                                                    [ok]

    Project entity contains 2 modules: entity, entity_token.
    entity-7.x-1.6 downloaded.                                                                                                                                  [ok]

    Project entityreference contains 2 modules: entityreference_behavior_example, entityreference.
    entityreference-7.x-1.1 downloaded.                                                                                                                         [ok]

    l10n_update-7.x-1.1 downloaded.                                                                                                                             [ok]

    link-7.x-1.3 downloaded.                                                                                                                                    [ok]

    Project metatag contains 15 modules: metatag_views, metatag_verification, metatag_twitter_cards, metatag_panels, metatag_opengraph, metatag_mobile, metatag_impo
    rter, metatag_google_plus, metatag_favicons, metatag_facebook, metatag_devel, metatag_dc, metatag_context, metatag_app_links, metatag.
    metatag-7.x-1.5 downloaded.                                                                                                                                 [ok]

    Project revisioning contains 3 modules: revisioning_ux, revisioning_scheduler, revisioning.
    revisioning-7.x-1.9 downloaded.                                                                                                                             [ok]

    semanticviews-7.x-1.0-rc2 downloaded.                                                                                                                       [ok]

    sqlsrv-7.x-1.3 downloaded.                                                                                                                                  [ok]

    token-7.x-1.6 downloaded.                                                                                                                                   [ok]

    Project views contains 2 modules: views, views_ui.
    views-7.x-3.11 downloaded.                                                                                                                                  [ok]

**Comment by greg-1-anderson** [comment]
Yes; your environment should behave consistently between `drush rebuild` and `drush make` without the need to change your environment variable settings.  Perhaps there is something misconfigured on your system? I do not run Windows; perhaps you could ask on Drupal Stack Exchange, and see if anyone is using `drush rebuild` successfully.

**Comment by w3wfr** [comment]
Hi Greg,

The point is that this patch is provided specifically for compatibility with Windows environment. Because Windows environment do not behave correctly and this is the way one can address it. 

I am working on a Microsoft full stack CI project including SQL Server and TFS, and this has been tested on several windows env. 

Regards. 
Alexandre

**Comment by greg-1-anderson** [comment]
But you are running Drush make on Windows as well, correct?

The point is, you must submit a PR that works equivalently with `drush make` and `drush rebuild` if you want us to merge it.  If your patch doesn't work well enough to do that, then you'll have to run patched.

**Comment by greg-1-anderson** [comment]
Some work is being done to get CI working with Drush and Windows at #1612.  If the unit tests start working, then it also stands to reason (presuming we have adequate coverage) that redispatches in `drush make` and `drush rebuild` should also work.

If you have time to help out on that issue, it would be super helpful.

**Comment by w3wfr** [comment]
OK: I will see this issue.
I need a little time to translate my inputs.

Regards.

**Comment by w3wfr** [comment]
Closing this PR and consider it as a working turn around that shouldn't be committed to drush as is. 

Joining the other conversation. 
Regards. 

Alexandre

**Comment by w3wfr** [comment]
Closing this PR and consider it as a working turn around that shouldn't be committed to drush as is. 

Joining the other conversation. 
Regards. 

Alexandre

**Pull request closed without merging**
