### PR TITLE
Update symfony to ~3.1

### PR DESCRIPTION
**Pull request by alexpott**
Core has updated Symfony - Drush needs to too.

### CODE REVIEW

**Comment by weitzman** [comment]
I dont see how this can go into Drush 8. Drush 8 supports D6 and D7 which happily run on PHP 5.4

**Comment by Berdir** [comment]
Can we just add the optional argument without forcing the new version? That might be enough to have it work with 3.1?

**Comment by alexpott** [comment]
I don't think that @Berdir's suggestion is going to work since if the drush autoloader gets in before the Drupal autoloader the wrong classes are going to be loaded :(

**Comment by greg-1-anderson** [comment]
Continue discussion at #2477

**Pull request closed without merging**
