### PR TITLE
Quote special characters in mysql user password -- Fix issue #5534

### PR DESCRIPTION
**Pull request by wdouglascampbell**
Quote all occurrences of single quotes, semi-colons and backslashes in database user password.

### CODE REVIEW

**Comment by weitzman** [comment]
In 12.x we recently fixed a similar issue with the DB name and special chars. See https://github.com/drush-ops/drush/pull/5167/files. So I think the right fix here is to honor the $quoted param. This change should go into 12.x and then 11.x if desired.

**Comment by wdouglascampbell** [comment]
I had not realized that the password could be quoted that way.  I will take a look and then submit a different pull request for 12.x.  How do I ensure it will also be applied to 11.x though?

**Comment by weitzman** [comment]
You open a PR for 12.x and when thats merged you open the equivalent for 11.x (unless I can cherry pick the commit cleanly - then I will just do that)

**Comment by wdouglascampbell** [comment]
Okay.  I discovered that using backticks does NOT work if the password contains a backtick.  I also realized after further testing that somehow my pull request didn't do what I intended.  I have fixed it and will resubmit it.

**Pull request closed without merging**
