### PR TITLE
field-create/field-delete: Filter bundles according to passed field name (11.x)

### LINKED ISSUE #5266: Respect `--field-name` in field:delete interaction
I'm running `drush field:delete  --field-name=field_state_organization_tax node` and Drush is offering me to pick from bundles that don't have the field thats been passed. /cc @DieterHolvoet

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #5266.

### CODE REVIEW

**Comment by weitzman** [comment]
@DieterHolvoet Is this ready for merge?

**Comment by DieterHolvoet** [comment]
I added a test case for the new `all-bundles` option, but I'm not sure how to add a test for this:
> I'm running drush field:delete  --field-name=field_state_organization_tax node and Drush is offering me to pick from bundles that don't have the field thats been passed.

**Comment by weitzman** [comment]
Reminder that this needs to also be merged into 12.x branch. Thanks.

**Comment by weitzman** [comment]
> I'm running drush field:delete --field-name=field_state_organization_tax node and Drush is offering me to pick from bundles that don't have the field thats been passed

Yes, its hard to test interactive features. You can skip the test for this piece.

**Comment by DieterHolvoet** [comment]
Okay, in that case I think this is good to go.

**Pull request merged**
