### PR TITLE
Update user cancel test to match upstream DCG changes

### PR DESCRIPTION
**Pull request by Chi-teck**
Content entity generator has got "translatable" option.
https://github.com/Chi-teck/drupal-code-generator/pull/10

### CODE REVIEW

**Comment by Chi-teck** [comment]
Btw, in the next DCG release content entity generator will get new "bundle" option which will likely break this test again.
https://github.com/Chi-teck/drupal-code-generator/pull/12

**Comment by greg-1-anderson** [comment]
Do you bump your major version for breaking changes?

**Comment by Chi-teck** [comment]
@greg-1-anderson, this is not a breaking change. I suppose `drush generate` command sill works well. The test failed because it is executing `content-entity` command programmatically simulating user interaction . This is not something that should be considered as public API.

**Comment by weitzman** [comment]
I upped composer.json and merged this.

**Pull request merged**
