### PR TITLE
Fixes #1151: Add option to include makefiles on the fly.

### LINKED ISSUE #1151: Option to include makefiles on the fly
It'd be nice to be able to add includes on the command-line when calling make. Specifically, this'd be useful in development environments. It'd avoid having to keep an extra stub makefile for development. I envision this just tacking on the included makefiles like a regular `includes[]` statement, but at the very end of the makefile being built.

### PR DESCRIPTION
**Pull request by ergonlogic**
Pretty simple implementation of #1151.

### CODE REVIEW

**Comment by ergonlogic** [comment]
@jhedstrom Thoughts?

Pretty straight-forward, imo. Also, a nice way to accomplish #456.

**Comment by ergonlogic** [comment]
Actually, after reviewing #1769 and #1770 again, this does *not* help with #456. We could look at using a similar approach with an `--overrides` option to merge over values in the makefile itself.

**Comment by jhedstrom** [comment]
This makes sense to me. Let's add an example to the docs though.

**Comment by ergonlogic** [comment]
Added docs for `--includes` and `--overrides`: https://github.com/drush-ops/drush/blob/dev/1151/docs/make.md#includes

**Comment by jhedstrom** [comment]
:+1:

**Pull request merged**
