### PR TITLE
Remove PHP 5.3 checks.

### PR DESCRIPTION
**Pull request by benjy**
Fix #1119

### CODE REVIEW

**Comment by weitzman** [comment]
Not sure about this. We discussed this in #595 and the d.o. issue that is linked from there. Drush7 still works on PHP 5.3.

**Comment by benjy** [comment]
Not sure either way, I guess Drush 7 only supporting 5.4 seems fair when Drupal 8 has a minimum requirement for 5.4. That said, this isn't a big issue, probably not the issue to finally drop 5.3.

The problem is with recent versions of xdebug, "php -r" gives a bus error. I've not tried to debug this.

Since this only started happening to me since I upgraded to 5.5 I think, how about a simple check like so?

    # If on PHP 5.3, disable magic_quotes_gpc and friends
    PHP_MINOR_VERSION="`\"$php\" -r 'print PHP_MINOR_VERSION;'`"
    if [ -z "$PHP_MINOR_VERSION" ]; then
      PHP_MINOR_VERSION=5
    fi

**Comment by greg-1-anderson** [comment]
Drush 7 still supports Drupal 6 and Drupal 7, so it will continue to support php 5.3.

For Drush 8, we have decided to remove php 5.3 support, regardless of Drupal 6 & 7 support, since 5.3 is getting pretty old now.

**Comment by weitzman** [comment]
There are a few more pieces that need updating. Grep the codebase for 5.3

**Pull request closed without merging**
