### PR TITLE
Add support in config import single command

### PR DESCRIPTION
**Pull request by rotemreiss**

### CODE REVIEW

**Comment by weitzman** [comment]
I dont see why we would use a new command for this. Could't we re-use --partial and let it point to a single file? Would that make the code flow too complex?

**Comment by rotemreiss** [comment]
I'll look into it once again, although I think that it crossed my mind.

**Comment by navneet0693** [comment]
This will really a lot helpful!

**Comment by mxr576** [comment]
Is there a new PR that would add this functionality to `drush cim --partial` as suggested in https://github.com/drush-ops/drush/pull/3629#issuecomment-409328264?

**Pull request closed without merging**
