### PR TITLE
config-export --skip-hashes

### PR DESCRIPTION
**Pull request by nevergone**
Issue #2197

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
+1 LGTM; tests sure would be nice.

**Comment by weitzman** [comment]
I'd like to see how the config_split integration finalizes before merging this.

**Comment by bircher** [comment]
config_split will work as long as the read/write interaction happens with the `config.storage.sync`, so it would work too.
But of course this functionality could also be achieved with a ConfigFilter from the config_filter module (which is a dependency for the next config_split release)

**Comment by weitzman** [comment]
Lets rely on config_filter instead of coding it here. Hope thats OK.

**Pull request closed without merging**
