### PR TITLE
batch:process experiment

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Make batch:process return unstructured list data, and produce no output by default.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
@MPParsley: Could you please test this and see if it resolves your issues with #3721?

Although UnstructuredListData behaves very similarly to an array, it is not exactly the same. I am uncertain how the return value from `batch:process` is used, and I don't know if our test coverage is complete enough to reveal any problems. If you discover anything that is broken by this PR, we could do a slightly less robust but more b/c thing and continue to just return the `array` here.

**Comment by MPParsley** [comment]
@greg-1-anderson, this looks good. I tested it and no issues came up.

**Comment by greg-1-anderson** [comment]
@weitzman Any thoughts on this? Do you think it's safe to change the output type of batch:process here?

**Comment by weitzman** [comment]
This is going in as part of #3758

**Pull request closed without merging**
