### PR TITLE
#1523 - Allow a dynamic schema on PostgreSQL

### PR DESCRIPTION
**Pull request by fiasco**
This hopefully fixes a breakage in PostgreSQL when using a non "public" schema.

### CODE REVIEW

**Comment by Renrhaf** [comment]
@fiasco did you try this one https://github.com/drush-ops/drush/pull/2567.patch ? I tested and it worked, I was wondering if you had done any other modifications that might be useful.

**Comment by fiasco** [comment]
@Renrhaf this is a pretty old PR that came long before #2567. So no I've not tested it and probably won't as this issue isn't currently affecting me.

**Comment by Renrhaf** [comment]
Ok, thanks ! Maybe we can close this one then ;)

**Comment by cafuego** [comment]
💙  @fiasco for saving my butt with this patch :-)

**Comment by ipumpkin** [comment]
need this for 8.x

**Pull request closed without merging**
