### PR TITLE
Config import partial

### PR DESCRIPTION
**Pull request by jhedstrom**
This is a start on #1163. It shouldn't be too much more work to allow for directory imports of partial config sets.

### CODE REVIEW

**Comment by jhedstrom** [comment]
Failure looks to be unrelated (honeypot needs updating since `_l()` was removed from 8.x).

**Comment by weitzman** [comment]
Looking good so far. Thanks for the test.

**Comment by weitzman** [comment]
I really like the --partial feature for config-import. I'm ambivalent on `config-edit --file` but if you think its valuable lets go with it. This passed tests so I think it can go in once @jhedstrom is happy with it.

**Comment by jhedstrom** [comment]
I've left the `config-edit --file` option in place for now.

**Pull request merged**
