### PR TITLE
Drush complete explanation

### PR DESCRIPTION
**Pull request by adrian-cid**
Added one example to users that don't know where and how configure the shell completion.

### CODE REVIEW

**Comment by weitzman** [comment]
In general this text is obsolete. The recommend way to add completion is to run `drush init`. That appends to your ~/.bashrc.

**Comment by adrian-cid** [comment]
do you prefer that I edit the file with the drush init command?

**Comment by adrian-cid** [comment]
I don't have in drush 5.10.0 the drush init command.

**Comment by weitzman** [comment]
Drush 5 is no longer supported. We just released 8.1.5

**Pull request closed without merging**
