### PR TITLE
Fixes #1265:  Define an exit status code for user aborts.

### LINKED ISSUE #1265: drush_user_abort() does not set an error exit code
If a drush command, for example `sql-drop`, is aborted by a user drush will return a success exit code. This makes scripting interactive solutions very difficult, as stderr must be captured and parsed.

The specific use case I am running in to is that I am scripting some drush commands as part of a build process. There are some specific commands that I would like the user to give confirmation to before proceeding (hence no yes-to-all). Drush currently provides no easy way (that I can find) for me to know a user abort vs regular execution path completed without scraping text.

I can understand the logic behind having a user abort treated as a success (the script did not fail). I think an `--abort-is-failure` argument would be very useful. If there is already some hidden command that provides this behavior feel free to let me know.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Here's a proposed patch that defines an exit code (75) that Drush returns if the user cancels.  Also defines a mechanism for Drush to set other exit codes, if desired.  (Currently, only "0" or "1" is ever returned.)

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
These tests fail due to a change in Drupal 8; they will all pass again when merged with master.

Let me know if you want to try this in Drush 7; it shouldn't hurt anything, although nonstandard.

**Comment by weitzman** [comment]
Well it would hurt any scripts that were expecting a success code after an abort. Do you think thats so rare or wrong that it is ignorable?

**Comment by greg-1-anderson** [comment]
I can't think of a situation where a script would want to continue after the user said abort.  If there was such a script, it could trap the error.  Of course, we break these scripts, but we do not guarentee that we won't across major version upgrades.  I think that the benefits outweigh the costs, but if you think that scripts that want to continue after an abort is more than an edge case, we can skip this.

**Comment by weitzman** [comment]
Makes sense. Feel free to merge this, when you are sure the test suite passes.

**Comment by greg-1-anderson** [comment]
Retested and merged.  Thanks.

**Pull request merged**
