### PR TITLE
Psr log 3

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Using Robo ^4 should allow Drush to use psr/log ^3 in contexts where Drupal 10 allows psr/log ^3.

Once confirmed, we can make a stable release of Robo 4.

### CODE REVIEW

**Review by weitzman — APPROVED** [review]
LGTM. You prob noticed that our Highest test is still using Log2 - https://app.circleci.com/pipelines/github/drush-ops/drush/3868/workflows/6d7b5744-9924-445e-9891-2cc41b708f10/jobs/23550?invite=true#step-108-9

**Comment by greg-1-anderson** [comment]
Yeah; to test, we need a Drupal 10 tag, branch or patch that allows psr/log ^3. With that, in theory, "highest" will install that version.

**Comment by greg-1-anderson** [comment]
Tested locally with https://github.com/greg-1-anderson/drupal-10-core-patched-psr-log-3.

**Comment by greg-1-anderson** [comment]
Drupal will hold us back to Robo ^3 until psr/log ^3 is allowed, so I will just merge this with the Robo ^4.0.0-alpha1 optional dependency until the Drupal psr/log ^3 patch is merged. Once that is confirmed working, I'll release a stable Robo 4.

**Pull request merged**
