### PR TITLE
Workaround for relative paths to commandfiles if drush is a phar (#4979)

### PR DESCRIPTION
**Pull request by mcdruid**
see https://github.com/drush-ops/drush/issues/4979#issuecomment-1249484507

### CODE REVIEW

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
LGTM, but minor point, could you please fix the indentation?

**Comment by greg-1-anderson** [comment]
Test errors appear unrelated.

**Comment by mcdruid** [comment]
Hopefully that's the indentation sorted; looks like a lot of the file has one leading tab then switches to spaces... :shrug:

**Comment by greg-1-anderson** [comment]
Looks good, thanks! Crossing fingers...

**Comment by greg-1-anderson** [comment]
I'll need to find time to do a release soon so that we can try this across a number of diverse environments.

**Pull request merged**
