### PR TITLE
Also search for configuration in a 'drush' directory above the webroot.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
See https://github.com/drupal-composer/drupal-project/issues/20

### CODE REVIEW

**Comment by weitzman** [comment]
Yeah, seems like a good idea. Lets update the sandwich file, the commandfile topic, and anywhere else that lists the search locations.

**Comment by helderco** [comment]
Is this working for you?

```
$ composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction
$ cd some-dir
$ echo '<?php $options["shell-aliases"]["devel"] = "en -y devel";' > drush/drushrc.php
$ cd web
$ drush status
[no config loaded]
```

Basically, if `/drush` (with `drushrc.php`) is outside of `/web` (drupal root), config isn't picked up. Neither are commands.

Note for the future: basing off of https://github.com/drupal-composer/drupal-project/tree/faac08e93b7bcdc74d660ec6b16a901f25755b4c

**Comment by weitzman** [comment]
This PR actually added commandfile searching in ../drush. I just pushed a commit which adds searching for config.

**Comment by greg-1-anderson** [comment]
I was just looking at this, and started with the test.  I'll commit the test for this shortly. Thanks.

**Comment by helderco** [comment]
Yeah, that fixed it. Thanks @weitzman.

**Pull request merged**
