### PR TITLE
Set extension name automatically when possible

### PR DESCRIPTION
**Pull request by Chi-teck**
This should work equally for module and theme generators.

### CODE REVIEW

**Comment by Chi-teck** [comment]
Added condition for current working directory when defining default value for name questions.
Do we still need _machineToLabel_ normalizer?

**Comment by weitzman** [comment]
I think we can remove machineToLabel normalizer. Good bye, brief friend!

**Comment by weitzman** [comment]
I really like this PR. Thanks.

At least part of the test fails here happen because [we explicitly pass a --directory](https://github.com/drush-ops/drush/blob/master/tests/annotatedCommandTest.php#L60) but that gets overwritten to modules/%. We should keep honoring --directory I think.

**Comment by Chi-teck** [comment]
DCG dumper did some alteration of $directory just before dumping files. I've just [moved](https://github.com/Chi-teck/drupal-code-generator/commit/f118cad6d6ed7ee4877ec2cc63486398b4c4059b?diff=unified) it to BaseGenerator class. Tests have become green but I am not sure if _directory_ option is still working.

**Comment by Chi-teck** [comment]
Also wonder if it would be a good idea to use absolute path for the directory.

**Comment by weitzman** [comment]
Merged this. We can keep improving it as needed. I dont follow what you are saying about absolute dir.

**Pull request merged**
