### PR TITLE
Site install interactive

### PR DESCRIPTION
**Pull request by serundeputy**
#2484

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Yeah, this looks good in concept -- but why isn't the results from Travis showing up here? I looked briefly and did not see the tests. If you can demonstrate that the tests are passing, then I'd be okay with merging this, porting to 8.x, and then doing the annotated conversion as a follow-on step.

If this were to be done to the annotated version of this command, `@hook interact` would be the thing to use to get the database credentials.

**Comment by greg-1-anderson** [comment]
Tests all green: +1

**Comment by weitzman** [comment]
I just merged #2466, so this needs a re-roll.

1. I'm not sure we can use `hook @interact` after all. If user is re-installing, he/she doesn't need to provide a db-url, and we shouldn't ask for one. We bootstrap to SITE level during 'pre' phase so I we know yet whether a db-url is needed during the interact phase. So, I think the code in pre phase like the PR is now.
1. We need to replace call to drush_set_error() with an exception and use $options instead of drush_get_option()

**Comment by weitzman** [comment]
ping @serundeputy

**Comment by serundeputy** [comment]
@weitzman thanks for the ping.

I've refactored this agains the new master and I've got the prompts working but I'm confused about what `$sql = SqlBase::create($commandData->input()->getOptions());` is expecting.

I've set the options via prompts but it is bailing out with unrecoverable errors.

Can you provide any insight?

thanks,
~Geoff

**Comment by weitzman** [comment]
The only setOption() that you should need is on db-url. You can use regular local variables to briefly store stuff like password, host, etc. 

When you pass `$commandData->input()->getOptions()` to `SqlBase::create()`, its important that 'db-url' is set in the returned array.

What errors are you seeing?

**Comment by serundeputy** [comment]
Thanks @weitzman 
refactored the PR tests are passing :)

Manually tested on current D8 `8.2.6` works great.

Manually tested on current D7 `7.54` but `si` is not working on `master` for D7 at all:

```
[warning] require(/Users/geoff/sites/flat/drupal-7.54/autoload.php): failed to open stream: No such file or directory drupal.inc:17
```

I think the D7 is a separate issue though.

~Geoff

**Comment by weitzman** [comment]
I moved the code around and then added this in 820fb5d. Thanks @serundeputy. Great to have some more interactivity in Drush.

**Comment by greg-1-anderson** [comment]
This could also have been done with `@hook interact`

**Pull request closed without merging**
