### PR TITLE
example.bashrc doesn't work with symlinks

### PR DESCRIPTION
**Pull request by jhedstrom**
Fix for #1171.

### CODE REVIEW

**Comment by jhedstrom** [comment]
Confirmed this doesn't work on linux either, but this pr fixes it.

**Comment by greg-1-anderson** [comment]
Existing commit works on my OSX system with a simlink--but I like the way yours looks better anyway, so we should commit this if it works in multiple platforms. I just need to remember to test this a couple of places. I seem to remember that some systems don't support the "[[ ]]" syntax, but I don't quite remember where the problem with this is.

What is the failure you are seeing with the current code?

**Comment by greg-1-anderson** [comment]
I just confirmed that the current checked-in code works both on OSX 10.10, and also on Ubuntu 12.04.

I also tested your proposed change, and found it worked in both places as well.  I wish I could remember where [[ was a problem.

I notice that complete.sh is using [[, so perhaps we can use it here as well.  Ah, looks like it was in #1115.

**Comment by greg-1-anderson** [comment]
Travis does not source example.bashrc, so I think we can go ahead and merge this PR.

**Comment by jhedstrom** [comment]
I detailed the failures in comments on commit 55deaf2 (not the clearest). The current code doesn't properly detect an absolute path, so assumes it is relative, resulting in the concatenation of the symlink + the real path, which then doesn't exist, so drush.complete.sh isn't sourced.

**Pull request merged**
