### PR TITLE
Replace abandoned Sami by Doctum

### PR DESCRIPTION
**Pull request by williamdes**
Replace Sami by [Doctum](https://github.com/code-lts/doctum)

### CODE REVIEW

**Comment by weitzman** [comment]
I'll give this a try soon. Thanks for reviving Sami!

**Comment by williamdes** [comment]
Hi @weitzman 
Did you have some time to give Doctum a try ?

**Comment by williamdes** [comment]
Hi
Maybe one of you would like to review this PR ?
cc @greg-1-anderson @tuutti

No pressure on you, just wanting that the right persons have the notification in time ;)

**Comment by greg-1-anderson** [comment]
I am strongly in favor of this, I just haven't had time to review the output.

**Comment by weitzman** [comment]
Merged, but unfortunately it failed to build. Any idea what went wrong? https://github.com/drush-ops/drush/runs/1167388909?check_suite_focus=true

**Comment by williamdes** [comment]
> Merged, but unfortunately it failed to build. Any idea what went wrong? https://github.com/drush-ops/drush/runs/1167388909?check_suite_focus=true

Sure:
```diff
- PATH=$HOME/bin:$PATH doctum.phar --ansi update doctum-config.php
+ PATH=$HOME/bin:$PATH php doctum.phar --ansi update doctum-config.php
```

**Pull request merged**
