### PR TITLE
Annotated command implementation of 'core-status' command.

### PR DESCRIPTION
**Pull request by greg-1-anderson**
The handling of default fields is not working right.  If --fields is not specified, an error is returned. If a valid list of --fields is given, they will be printed.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Fixed one bug in the upstream, but one more remains. All of the possible fields are displayed, even if some fields contain no data. Fields with no data should be omitted from the output.

**Comment by weitzman** [comment]
@greg-1-anderson - Does your recent output-formatters work fix #130 for annotated commands?

**Comment by greg-1-anderson** [comment]
@weitzman Yes, with the addition of the --include-field-labels option to the status command. This could be a global option, perhaps.

Having a hard time figuring out why the tests are failing. Sometimes the site-under-test ends up at `drush-sandbox/web/web` instead of `drush-sandbox/web`. It seems that maybe archive-dump or archive-restore or something else in the tests is relying on the behavior of `drush core-status` that I am not completely emulating. This is not a great design. Might want to fix it by changing the way the tests work.

**Comment by greg-1-anderson** [comment]
Okay, got the tests using only "standard" forms, no shortcuts, when using `core-status`.

Not implemented yet:

- [ ] --format=tsv blows up (does not handle non-string cell data)
- [ ] --format=csv not working perfectly (again, array handling a bit off)
- [ ] Using arguments in place of --fields=... not implemented (drop support for this?)
- [ ] --pipe selects tsv; should select json to maintain backwards compatibility

**Comment by weitzman** [comment]
I think we can drop support for the argument and drop support for --pipe
option. Folks can be explicit.

**Comment by weitzman** [comment]
@greg-1-anderson  - I'm OK if we merge this without all that checklist complete.

**Comment by greg-1-anderson** [comment]
Latest commit should take care of the primary backwards-compatibility issues.  Let's see how the tests fare.

**Pull request merged**
