### PR TITLE
Fix site-install command

### PR DESCRIPTION
**Pull request by webflo**
- Handle exception from drupal_get_profile when container ist not initialized and db connection not defined yet.
- Reimplement distribution detection (reverts 7b609a4)

---

I did some debugging for https://github.com/drupal-composer/drupal-project/pull/270 and found the root cause in commit 7b609a4.

### CODE REVIEW

**Comment by weitzman** [comment]
Thanks for debugging. 

I am under the impression that Drush doesn't need the distro code anymore because core doesn't write profile to settings.php if its read only.

**Comment by webflo** [comment]
The correct the Drupal installer takes care of it (``install_write_profile()``). But this patch is about reading the install profile from settings prior installation to detect which install profile should be used. 

- ``drupal_get_profile()`` reads it from the database or settings file.
- ``_install_select_profile()`` reads its from profile metadata (distro, or only one profile etc)

**Comment by webflo** [comment]
The important change is ``drupal_get_profile()``. Drush called it before, but it throw a exception because the container was not initialized and not db connection was available.

**Comment by weitzman** [comment]
Thanks @webflo

**Pull request merged**
