### PR TITLE
In queue:run, set the lease time for a claimed item to the remaining execution time

### PR DESCRIPTION
**Pull request by lems3**
Set the lease time for a claimed item to the remaining execution time of the queue instead of using the default of 60 minutes, to have a similar behavior than a queue processed by cron.

### CODE REVIEW

**Comment by weitzman** [comment]
Seems fine to me. Input welcome @juampynr @davereid @damiankloip

**Comment by weitzman** [comment]
If you dont pass a time limit, then `remaining` check fails and nothing gets run?

**Comment by lems3** [comment]
Unless mistaken (I could be), when you're not passing a time limit, the first while condition resolve to true, with the !$time_limit clause.
Otherwise, shouldn't the old condition, time() < $end, cause the same issue ?

**Comment by damiankloip** [comment]
Hmm, Not sure. As `self::REQ` is the default value. Which is an alias of `\Symfony\Component\Console\Input\InputOption::VALUE_REQUIRED` which is `2`.

**Comment by juampynr** [comment]
Looking at the diff I don't see major changes in the resulting logic. @lems3: can you add tests?

**Comment by m4olivei** [comment]
Here is an alternative that builds on this: https://github.com/drush-ops/drush/pull/4083.

I've added the generic exception handling that core has and added a test.

**Comment by weitzman** [comment]
@juampynr @damiankloip - see new PR.

**Comment by greg-1-anderson** [comment]
Closing in favor of #4083.

**Pull request closed without merging**
