### PR TITLE
Improve the log of the updatedb command

### LINKED ISSUE #3296: Improve logging when performing site updates
Here is an example log output I pulled from one of our test servers:

```
    [drush] Executing command: /srv/project/vendor/bin/drush --root="/srv/project/web" --yes updatedb 
 ----------- ------------------ ------------- ---------------------------------  
  Module      Update ID          Type          Description                       
 ----------- ------------------ ------------- ---------------------------------  
  collectio   show_events_face   post-update   Updates the collection content    
  n           t                                field to show the events facet.   
  joinup_co   install_joinup_i   post-update   Enable the Joinup Invite          
  re          nvite                            module.                           
  joinup_co   install_smart_tr   post-update   Enable the Smart Trim module.     
  re          im                                                                 
  joinup_co   move_contact_for   post-update   Move the contact form             
  re          m_attachments                    attachments under the private     
                                               scheme.                           
  joinup_di   enable_changed_f   post-update   Enable the Changed Fields API     
  scussion    ields                            module.                           
  joinup_mi   copy_about_text_   post-update   Copy the about text to            
  grate       ctt_spain                        distributions for CTT Spain       
                                               [ISAICP-4057].                    
  joinup_mi   same_name_distri   post-update   Fix distribution files with the   
  grate       bution_files                     same name [ISAICP-3968].          
  joinup_su   install_flag       post-update   Install the 'flag' module.        
  bscriptio                                                                      
  n                                                                              
  joinup_us   add_subscribe_di   post-update   Adds permissions to subscribe     
  er          scussion_permiss                 to discussions for                
              ions                             authenticated users.              
 ----------- ------------------ ------------- ---------------------------------  
 
 // Do you wish to run the specified pending updates?: yes.                      
 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Could not apply Half width image style to  because the style does not support it. 
 [warning] Could not apply Full width image style to  because the style does not support it. 
 [warning] Missing file with ID 508501. ImageItem.php:328 
 [ok] Post updating collection 
 [ok] Post updating joinup_core 
 [ok] Post updating joinup_core 
 [ok] Post updating joinup_core 
 [ok] Post updating joinup_discussion 
 [ok] Post updating joinup_migrate 
 [ok] Post updating joinup_migrate 
 [ok] Post updating joinup_subscription 
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [warning] Illegal string offset 'query' UpdateDBCommands.php:374 
 [notice] D 
 [notice]  
 [warning] Illegal string offset 'query' UpdateDBCommands.php:374 
 [notice] C 
 [notice]  
 [notice]  
 [notice]  
 [notice]  
 [notice]  
Array   Array   Array   Array   Array   Array 
 [success] Cache rebuild complete. 
 [success] Finished performing updates. 
```

The log shows evidence of bugs in the update command, and the existing output can be improved:

* The name of the post_update hook that is being executed is not output. Instead it outputs the name of the module that contains the hooks repeatedly.
* There are a bunch of empty notices being output.
* Some puzzling notices that contain single letters (`D` and `C`).
* PHP warnings `Illegal string offset 'query' UpdateDBCommands.php:374`.
* `Array Array Array ...` ??
* The final line proclaims that the updates were finished successfully but this is not correct, an error occurred during one of the updates, and the last one was not even executed. The log should reflect this information.

### PR DESCRIPTION
**Pull request by pfrenssen**
This partially fixes #3296.

The output of the `updatedb` command can be quite confusing, since misleading messages are being output, and incorrect statuses are being communicated.

Here is some example output from the current update test suite:

```
 [notice] Executing woot_update_8101
 [ok] Performing woot_update_8101
 [notice] Executing woot_update_8102
 [error]  8102 error 
 [ok] Performing woot_update_8102
 [notice] woot_update_8101
 [error]  Failed batch process: woot_update_8102 
 [error]  Finished performing updates.
```

* There appears to be duplicated information about "executing" and "performing" each individual update. In fact when the log mentions that it is "Performing hook_update_x" the update has already finished.
* Update 8102 failed, so there should not be any `[ok]` associated with it.
* It shouldn't mention that the "batch process" failed. That the batch API is used behind the scenes is an implementation detail and not important to mention in the log output.

Edit: Note that the scope of this PR is solely to change the existing messages so they are less confusing. The order of the messages is being corrected in #3302, missing errors are in #3308.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Test fails as expected. Now committing the fix.

**Comment by claudiu-cristea** [comment]
So, i assume that #3302 should be closed, right?

**Comment by claudiu-cristea** [comment]
I've added 525f33b to log also the failures.

**Comment by pfrenssen** [comment]
This doesn't look right, now the messages are in the wrong order. The initial test proved that the output was there, and in the right place (during the execution):

```
[notice] Update started: woot_update_8102
[error] This is the exception message thrown in woot_update_8102
[error] Update failed: woot_update_8102
```

With your patch the error is still there but in the wrong location.

Can you give some more info on what you are trying to solve? Maybe you didn't have an exception but a different (uncatchable?) error?

This issue is not about adding things to the log that are not already there, but about improving the existing messages so they are less confusing. If you are not seeing something important, we can best fix this in a separate issue.

> So, i assume that #3302 should be closed, right?

No, #3302 is also a different scope, it's about making sure the log messages are appearing in the correct order. This is about improving the messages.

**Comment by pfrenssen** [comment]
I've discussed this with @claudiu-cristea. I'm going to revert this to the previous state so the PR and split off the missing exception to a separate issue. It seems that only exceptions in `hook_update_N()` are correctly logged, those in post-updates are not.

Follow up issue to fix the missing error message is #3308. A copy of the original fix by @claudiu-cristea is here: https://github.com/pfrenssen/drush/commits/missing-exception

**Comment by claudiu-cristea** [comment]
Discussed with @pfrenssen and I will review this PR tomorrow morning so it can be quickly ready for the 9 stable release.

**Comment by claudiu-cristea** [comment]
Good job! I rerolled the PR. @weitzman, @greg-1-anderson I've tested this on out project wit this PR the log messages are displayed in the correct order. This is proved also by the test. Good to go.

**Comment by weitzman** [comment]
Merged in #3310

**Pull request closed without merging**
