### PR TITLE
#1493 - override alias records with cli context options

### PR DESCRIPTION
**Pull request by blazindrop**
First stab at fixing the issue where command line arguments (especially --uri) can't override site aliases.

### CODE REVIEW

**Comment by weitzman** [comment]
ping @greg-1-anderson.

This one is biting some folks. I did some tests with this command `drush @d7 --uri=http://foo pm-updatecode`. Below is the site alias @d7:

```
$aliases['foo'] = array(
 'root' => '/Users/moshe.weitzman/htd/d7',
 'uri' => 'http://mm/d7',
);
```

My expectation is that the --uri=http://foo on the CLI is propagated to backend calls but that's not happenning on drush7 or drush8. It *is* happenning on drush6. Is this by design? The non-overridden --uri is visible in log excerpt below:

```
Backend invoke: /usr/local/bin/php /Users/moshe.weitzman/c/h/drush/drush.php --php=/usr/local/bin/php  --backend=2 --verbose --debug --no  --root=/Users/moshe.weitzman/htd/d7 --uri=http://mm/d7  pm-updatestatus 2>&1
```
This PR fixes the bug for some commands like `drush @foo --uri=http://buytaert.net browse` but not the pm-updatecode example above.

**Comment by greg-1-anderson** [comment]
Yeah, I looked at that PR a few days ago, and my initial impression was, "why is the existing code doing it that way?"  Adding explicit cli overrides on top of an explicit alias override (band-aid on the band-aid) looks like too much doctoring.  I was wondering if it would hurt too much to just pull off the band-aid, and see if we can heal the owie some other way. The existing Drush context priority logic should be right most of the time; I'm not sure why it is not in this case.  (n.b. cli overrides alias if we just take off the band-aid).

**Comment by weitzman** [comment]
The PR changes drush_redispatch_get_options() but thats not even called for `drush @d7 --uri=http://foo pm-updatecode`

**Comment by greg-1-anderson** [comment]
So, I think the fix for `drush_redispatch_get_options()` should be:

`$options = $cli_context + drush_get_context('specific') + $alias_options;`

I think alias options should just be all of the options.  Then, below, in the part where we get the command in order to filter out options that are not defined in the command definition, we should union in the global options, and treat all options uniformly.

It does not make any sense that we should filter options based on where they come from.  What matters is: (a) which contexts are relevant, (b) what their relative priority is, and (c) which options should be sent on to the remote command.  We should just do that.

I don't know about the code path that does not go through `drush_redispatch_get_options()`, though.

**Comment by weitzman** [comment]
I think the other code path has to do with the alias 'self'. In drush6 that had a --uri value from cli but in 7/8 it has alias' value.

**Comment by ElijahLynn** [comment]
This one is biting us too, Acquia just did a drush default switch from drush6 to drush8. Previously working Cloud Hooks were working fine and now they are broken for our particular setup. We have a multisite setup and the Cloud Hooks run from $HOME. The scripts are calling drush --uri with the old 'foldername' for drush 6 but when I try the recommend full URI that should map to the sites.php it shows it initiates the sites in the right folder but then as you say it doesn't pass that to the backend and I get the original URI in the alias file.

I know you guys know this but just posting this here for the search engines.

**Comment by weitzman** [comment]
Just posted a proposed fix for both the pm-updatecode code path and the drush_redispatch_get_options() code path at #1924. Please test and report back. let's closer this and discuss there.

Also could use some unit tests.

**Pull request closed without merging**
