### PR TITLE
change $_SERVER['REQUEST_METHOD'] default to 'GET'

### PR DESCRIPTION
**Pull request by kentr**
For #2511

### CODE REVIEW

**Comment by kentr** [comment]
Happy to write a test for this, but I need suggestions on the details (what specifically to assert, etc).

**Comment by kentr** [comment]
@weitzman What are the steps for getting this into a stable 8.x version?

**Comment by pjcdawkins** [comment]
Thanks for the PR @kentr, this fixed a problem for me with the simple_sitemap module, which took a very long time to debug (https://www.drupal.org/node/2828238).

I'll second that having it in a stable release would be much appreciated.

**Comment by weitzman** [comment]
We create stable releases every couple months unless an emergency arises.

**Comment by kentr** [comment]
@weitzman Thx.

I'm don't know what the criteria are for "emergency" status, but for consideration in that triage:

This issue will break sites...  It prevented my client from upgrading Drupal core b/c the upgrade broke their theme.

It's also [affecting the Simple XML Sitemap module](https://www.drupal.org/node/2828238).

I would guess that the average drush user doesn't understand the intricacies of installing a dev version or patching their project-specific version.

**Comment by greg-1-anderson** [comment]
The situation in #2511 sounds severe enough to me to warrant a release of 8.x. Our last release, 8.1.8 was 29 Nov, so we're about due anyway.

**Pull request merged**
