### PR TITLE
Try out Drupal 9 support

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Drupal 9 for Drush 8.

### CODE REVIEW

**Comment by weitzman** [comment]
Looks like Circle didnt run the full suite.

**Comment by weitzman** [comment]
Oh this is for drush8. Lets chat.

**Comment by greg-1-anderson** [comment]
It is not possible to make more progress here until updates.drupal.org is advertising Drupal 9 versions.

**Comment by greg-1-anderson** [comment]
I hacked around in the `pm-*` code and sorta-kinda made it work with the new `all` endpoint, so tests are getting a little farther.

I skipped the tests that require a version of devel for Drupal 9. Now the test suite is down to just two failures.

**Pull request merged**
