### PR TITLE
Workaround for #2065: Additional use_pcntl_exec check

### PR DESCRIPTION
**Pull request by bleeDev**
Workaround for #2065

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
This allows folks to use the workaround for  #2065, but it does not fix #2065. See #2815.

I'm still in favor of merging, if the tests pass.

**Comment by weitzman** [comment]
doesn't the PR currently say to use pcntl_exec even when it is in the disable_functions list?

**Comment by bleeDev** [comment]
@weitzman You are correct, updated with correct logic.

**Comment by jhedstrom** [comment]
Does this need to go into master as well?

**Comment by weitzman** [comment]
This code is removed from master. There is no finder anymore. Note the
drush-launcher repo.

**Pull request merged**
