### PR TITLE
Add --items-limit option to queue:run command

### LINKED ISSUE #4120: Add --items-limit option to queue:run command
**Describe the solution you'd like**
As a Drush user I would like to be able to specify how many items to be processed in the queue-run command.

**Additional context**
I'm working on a script that iterates through all sites on a very large (80+) multisite codebase and clears as many items from a given queue shared across these sites as it can in a given time limit by processing one item of each site's queue per iteration.

**Example:**
drush custom-multisite-iterator-command --total-time-limit=60 queue:run --items-limit=1 my_queue

- custom-multisite-iterator-command: A custom command that iterates through a given site list and executes a given command across these sites as many times as possible in the given time limit.

### PR DESCRIPTION
**Pull request by jose-oliveira**
Fixes #4120 .

### CODE REVIEW

**Comment by jfarrell** [comment]
@weitzman any chance you could please review and help move this PR forward?

**Comment by weitzman** [comment]
Seems reasonable to me. Ping @juampynr, @damiankloip

**Comment by juampynr** [comment]
Looks good to me!

**Comment by weitzman** [comment]
Merged and Backported to 9.x

**Pull request merged**
