### PR TITLE
Temporary work-around to get tests passing...

### PR DESCRIPTION
**Pull request by ergonlogic**
… pending patch to Libraries module.

### CODE REVIEW

**Comment by jonhattan** [comment]
I think this is overly complicated. Should be easier to switch to another project.

Le'ts try to ping @tstoeckler that I've seen around drush queue... @tstoeckler plz https://www.drupal.org/node/2557419 :smile:

**Comment by jhedstrom** [comment]
Temporary fix looks fine. Is this failure new?

```
1) Unish\generateMakeCase::testGenerateMake
Undefined property: Unish\generateMakeCase::$EXIT_SUCCESS
```

**Comment by ergonlogic** [comment]
@jonhattan BTW, @weitzman asked us to fix the failing tests via email, and expressed a preference for sticking with Libraries.

@jhedstrom pebkac w/ calling PHP class constants.

**Comment by ergonlogic** [comment]
Ok, tests are passing again. I'm going to squash these commits, to simplify reverting.

**Comment by ergonlogic** [comment]
For reference, the relevant commit to master is eff4fd2d02

**Comment by tstoeckler** [comment]
Sorry @everyone for taking so long to respond! Libraries API is fixed now.

**Pull request closed without merging**
