### PR TITLE
Move to cmi overrides.

### PR DESCRIPTION
**Pull request by benjy**
Thanks to @chx for suggesting that we can simply use CMI overrides. Simplifies the code and allows us to support more than just overriding source/destination config.

### CODE REVIEW

**Comment by chx** [comment]
You should probably merge in the original settings overrides

**Comment by benjy** [comment]
Sorry for the delay on this, I fly out for DrupalSouth today but i'll take a look at this in the sprint on Saturday.

**Comment by benjy** [comment]
OK, i took a look at this and based on Config::getOriginal() it would seem that the merging is already handled.

**Comment by benjy** [comment]
OK, this should be good.

**Comment by chx** [comment]
Yes, this looks very nice.

**Pull request merged**
